In [1]:
import pandas as pd

In [9]:
news_values = pd.read_csv('../data/csv/news_from_2024-01-01_to_2026-03-04.csv')

In [4]:
news_values

,id,publisher,title,author,published_utc,article_url,tickers,image_url,description,keywords,insights,amp_url
0,971fcae532f2cb16e718a30402fefccfd0c2790d3d103d...,"{'name': 'GlobeNewswire Inc.', 'homepage_url':...",Bitget Wallet amplía su tarjeta cripto sin com...,Na,2026-03-04T22:39:00Z,https://www.globenewswire.com/news-release/202...,['MA'],https://ml-eu.globenewswire.com/Resource/Downl...,Bitget Wallet has launched a crypto payment ca...,"['crypto payment card', 'stablecoins', 'USDC',...","[{'ticker': 'MA', 'sentiment': 'neutral', 'sen...",NaN
1,afcdfc8597a08d36276ccaf4df4df19a86b0800650d5b0...,"{'name': 'Investing.com', 'homepage_url': 'htt...",Meta Is Bringing Back Stablecoin Payments—This...,Leo Miller,2026-03-04T17:28:00Z,https://www.investing.com/analysis/meta-is-bri...,"['META', 'MA', 'V']",https://i-invdn-com.investing.com/redesign/ima...,Meta plans to launch a stablecoin with a third...,"['stablecoin', 'Meta', 'cryptocurrency payment...","[{'ticker': 'META', 'sentiment': 'positive', '...",https://m.investing.com/analysis/meta-is-bring...
2,1ba810eae81c9e5f5e78b42722fd8be1829672e9bd2db9...,"{'name': 'Investing.com', 'homepage_url': 'htt...",SoFi Gains Traction as Mastercard Deal Brings ...,Timothy Fries,2026-03-04T16:01:00Z,https://www.investing.com/analysis/sofi-gains-...,"['SOFI', 'MA']",https://i-invdn-com.investing.com/redesign/ima...,SoFi Technologies announced an enhanced partne...,"['stablecoin', 'SoFiUSD', 'global payments', '...","[{'ticker': 'SOFI', 'sentiment': 'positive', '...",https://m.investing.com/analysis/sofi-gains-tr...
3,516d0af2eed7abd373aad711ad6beaf02e7ade72ed2338...,"{'name': 'GlobeNewswire Inc.', 'homepage_url':...",Bitget Wallet Expands Zero-Fee Crypto Card in ...,Globe Newswire,2026-03-04T02:44:00Z,https://www.globenewswire.com/news-release/202...,['MA'],https://ml-eu.globenewswire.com/Resource/Downl...,Bitget Wallet has launched a cryptocurrency pa...,"['crypto payment card', 'stablecoins', 'USDC',...","[{'ticker': 'MA', 'sentiment': 'neutral', 'sen...",NaN
4,ce06d9c128a7ff73b4f51d3a5a9430f55c6fa3919a136f...,"{'name': 'The Motley Fool', 'homepage_url': 'h...","Stock Market Today, March 3: SoFi Technologies...",Emma Newbery,2026-03-03T22:20:48Z,https://www.fool.com/coverage/stock-market-tod...,"['SOFI', 'MA', 'LC', 'UPST']",https://g.foolcdn.com/image/?url=https%3A%2F%2...,SoFi Technologies rose 1.22% to $18.61 on Marc...,"['stablecoin', 'fintech', 'insider buying', 'd...","[{'ticker': 'SOFI', 'sentiment': 'positive', '...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
945,hgPAbEhurZephLC6qTe77gHbaAAFaPYuNdGXSEnR1P4,"{'name': 'Zacks Investment Research', 'homepag...",Mastercard (MA) & Geidea Partner to Drive Paym...,Zacks Equity Research,2023-07-18T15:58:00Z,https://www.zacks.com/stock/news/2123099/maste...,"['MA', 'V', 'WEX', 'DLO']",https://staticx-tuner.zacks.com/images/article...,Mastercard (MA) collaborates with Geidea to pr...,NaN,NaN,https://www.zacks.com/amp/stock/news/2123099/m...
946,OErIFHL3nQI2n06kDw44IGK1r9ZyvbskSvS_LPm2USA,"{'name': 'Zacks Investment Research', 'homepag...",3 Payment Stocks Gaining From Improving Consum...,Tirthankar Chakraborty,2023-07-18T10:40:00Z,https://www.zacks.com/stock/news/2122627/3-pay...,"['MA', 'V', 'PYPL']",https://staticx-tuner.zacks.com/images/article...,"Payment processors like Visa (V), Mastercard (...",NaN,NaN,https://www.zacks.com/amp/stock/news/2122627/3...
947,3IUGXOeHB55VkBjocFD-iQnAVJ3wfl4hoqYnr_UBn58,"{'name': 'The Motley Fool', 'homepage_url': 'h...",3 Warren Buffett Stocks That Everyone Should Own,newsfeedback@fool.com (Royston Yang),2023-07-18T09:33:00Z,https://www.fool.com/investing/2023/07/18/3-wa...,"['AAPL', 'BRK.A', 'BRK.B', 'MA', 'FND']",https://g.foolcdn.com/editorial/images/739993/...,Let's take a page from the Oracle of Omaha's i...,['investing'],NaN,NaN
948,wpvx5wjVuWuenU-979enj0RjmH0u7Z_632FYzmjxTTA,"{'name': 'Zacks Investment Research', 'homepag...",MasterCard (MA) Stock Sinks As Market Gains: W...,Zacks Equity Research,2023-07-17T21:45:18Z,https://www.zacks.com/stock/news/2122405/maste...,['MA'],https://staticx-tuner.zacks.com/images/default...,MasterCard (MA) closed the most recent trading...,NaN,NaN,https://www.zacks.com/amp/stock/news/2122405/m...
949,U4r00hhypLGaEeLAxqyaa6ux9FmkVToV8Di0YH4uAFc,"{'name': 'Zacks Investment Research', 'homepag...",Mastercard (MA) & DTS Unite to Minimize Digita...,Zacks Equity Research,2023-07-17T17:12:00Z,https://www.zacks.com/stock/news/2122338/maste...,"['MA', 'V', 'WEX', 'DLO']",https://staticx-tuner.zacks.com/images/article...,Mastercard (MA) collaborates with DTS to provi...,NaN,NaN,https://www.zacks.com/amp/stock/news/2122338/m...

In [6]:
news_values['insights'].loc[55]

"[{'ticker': 'AXP', 'sentiment': 'positive', 'sentiment_reasoning': 'Outperformed peers with 40% share price increase, lower valuation metrics, record quarterly revenue, raised full-year sales guidance, and lower credit losses due to affluent client base'}, {'ticker': 'V', 'sentiment': 'neutral', 'sentiment_reasoning': 'Reported solid earnings with revenue and EPS growth, but guided to lower expected revenue and anticipated higher operating expenses in 2026'}, {'ticker': 'MA', 'sentiment': 'neutral', 'sentiment_reasoning': 'Achieved top and bottom-line beat with strong revenue growth, but faces potential revenue headwind from Capital One migration and higher valuation compared to peers'}]"

In [39]:
news_values2 = pd.read_csv('../data/csv/final.csv')

In [32]:
news_values2

,date,title,real_news,ma,axp,cof,es_ingles
0,2026-03-04T22:39:00Z,Bitget Wallet amplía su tarjeta cripto sin com...,Bitget Wallet has launched a crypto payment ca...,0.0,0.0,0.0,True
1,2026-03-04T17:28:00Z,Meta Is Bringing Back Stablecoin Payments—This...,Meta plans to launch a stablecoin with a third...,0.0,0.0,0.0,True
2,2026-03-04T16:01:00Z,SoFi Gains Traction as Mastercard Deal Brings ...,SoFi Technologies announced an enhanced partne...,1.0,0.0,0.0,True
3,2026-03-04T02:44:00Z,Bitget Wallet Expands Zero-Fee Crypto Card in ...,Bitget Wallet has launched a cryptocurrency pa...,0.0,0.0,0.0,True
4,2026-03-03T22:20:48Z,"Stock Market Today, March 3: SoFi Technologies...",SoFi Technologies rose 1.22% to $18.61 on Marc...,1.0,0.0,0.0,True
...,...,...,...,...,...,...,...
933,2023-07-18T15:58:00Z,Mastercard (MA) & Geidea Partner to Drive Paym...,Mastercard (MA) collaborates with Geidea to pr...,0.0,0.0,0.0,True
934,2023-07-18T10:40:00Z,3 Payment Stocks Gaining From Improving Consum...,"Payment processors like Visa (V), Mastercard (...",0.0,0.0,0.0,True
935,2023-07-18T09:33:00Z,3 Warren Buffett Stocks That Everyone Should Own,Let's take a page from the Oracle of Omaha's i...,0.0,0.0,0.0,True
936,2023-07-17T21:45:18Z,MasterCard (MA) Stock Sinks As Market Gains: W...,MasterCard (MA) closed the most recent trading...,0.0,0.0,0.0,True
937,2023-07-17T17:12:00Z,Mastercard (MA) & DTS Unite to Minimize Digita...,Mastercard (MA) collaborates with DTS to provi...,0.0,0.0,0.0,True

In [28]:
for i in news_values.loc[news_values['published_utc'] == '2026-03-04T17:28:00Z']['insights']:
    print(i)

[{'ticker': 'META', 'sentiment': 'positive', 'sentiment_reasoning': "Meta's renewed stablecoin initiative is positioned favorably with improved regulatory conditions (GENIUS Act), growing market adoption ($30B to $300B in stablecoin supply since 2020), and clear business benefits including reduced cross-border payment costs, enhanced creator incentives, and potential new transaction-based revenue streams. The strategy leverages Meta's significant international revenue (56% from outside US/Canada) and could strengthen its core advertising business through increased engagement."}, {'ticker': 'MA', 'sentiment': 'neutral', 'sentiment_reasoning': "Mastercard is mentioned only as a historical reference point—it left Meta's Libra Association in 2019. The article does not discuss current implications for Mastercard regarding Meta's new stablecoin plans."}, {'ticker': 'V', 'sentiment': 'neutral', 'sentiment_reasoning': "Visa is mentioned only as a historical reference point—it left Meta's Libra Association in 2019. The article does not discuss current implications for Visa regarding Meta's new stablecoin plans."}]

In [5]:
news_values2.loc[news_values2['es_ingles'] == True]

,date,title,real_news,ma,axp,cof,es_ingles
0,2026-03-04T22:39:00Z,Bitget Wallet amplía su tarjeta cripto sin com...,Bitget Wallet has launched a crypto payment ca...,0.0,0.0,0.0,True
1,2026-03-04T17:28:00Z,Meta Is Bringing Back Stablecoin Payments—This...,Meta plans to launch a stablecoin with a third...,0.0,0.0,0.0,True
2,2026-03-04T16:01:00Z,SoFi Gains Traction as Mastercard Deal Brings ...,SoFi Technologies announced an enhanced partne...,1.0,0.0,0.0,True
3,2026-03-04T02:44:00Z,Bitget Wallet Expands Zero-Fee Crypto Card in ...,Bitget Wallet has launched a cryptocurrency pa...,0.0,0.0,0.0,True
4,2026-03-03T22:20:48Z,"Stock Market Today, March 3: SoFi Technologies...",SoFi Technologies rose 1.22% to $18.61 on Marc...,1.0,0.0,0.0,True
...,...,...,...,...,...,...,...
933,2023-07-18T15:58:00Z,Mastercard (MA) & Geidea Partner to Drive Paym...,Mastercard (MA) collaborates with Geidea to pr...,0.0,0.0,0.0,True
934,2023-07-18T10:40:00Z,3 Payment Stocks Gaining From Improving Consum...,"Payment processors like Visa (V), Mastercard (...",0.0,0.0,0.0,True
935,2023-07-18T09:33:00Z,3 Warren Buffett Stocks That Everyone Should Own,Let's take a page from the Oracle of Omaha's i...,0.0,0.0,0.0,True
936,2023-07-17T21:45:18Z,MasterCard (MA) Stock Sinks As Market Gains: W...,MasterCard (MA) closed the most recent trading...,0.0,0.0,0.0,True
937,2023-07-17T17:12:00Z,Mastercard (MA) & DTS Unite to Minimize Digita...,Mastercard (MA) collaborates with DTS to provi...,0.0,0.0,0.0,True

In [13]:
len(news_values2.loc[news_values2['ma'] == 1])

164

In [21]:
print(news_values2['date'].dtype)

object

In [40]:
news_values2['date'] = pd.to_datetime(news_values2['date'], dayfirst=True)

# Paso 2: Convertirla al formato visual con guiones
news_values2['date'] = news_values2['date'].dt.strftime('%d-%m-%Y')

ValueError: time data "2026-02-27T08:05:00Z" doesn't match format "%Y-%d-%mT%H:%M:%S%z", at position 6. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [29]:
type(news_values2['date'].loc[0])

str

In [41]:
news_values2['date'] = pd.to_datetime(news_values2['date'])
news_values2['date'] = news_values2['date'].dt.normalize()

In [42]:
news_values2

,date,title,real_news,ma,axp,cof,es_ingles
0,2026-03-04 00:00:00+00:00,Bitget Wallet amplía su tarjeta cripto sin com...,Bitget Wallet has launched a crypto payment ca...,0.0,0.0,0.0,True
1,2026-03-04 00:00:00+00:00,Meta Is Bringing Back Stablecoin Payments—This...,Meta plans to launch a stablecoin with a third...,0.0,0.0,0.0,True
2,2026-03-04 00:00:00+00:00,SoFi Gains Traction as Mastercard Deal Brings ...,SoFi Technologies announced an enhanced partne...,1.0,0.0,0.0,True
3,2026-03-04 00:00:00+00:00,Bitget Wallet Expands Zero-Fee Crypto Card in ...,Bitget Wallet has launched a cryptocurrency pa...,0.0,0.0,0.0,True
4,2026-03-03 00:00:00+00:00,"Stock Market Today, March 3: SoFi Technologies...",SoFi Technologies rose 1.22% to $18.61 on Marc...,1.0,0.0,0.0,True
...,...,...,...,...,...,...,...
933,2023-07-18 00:00:00+00:00,Mastercard (MA) & Geidea Partner to Drive Paym...,Mastercard (MA) collaborates with Geidea to pr...,0.0,0.0,0.0,True
934,2023-07-18 00:00:00+00:00,3 Payment Stocks Gaining From Improving Consum...,"Payment processors like Visa (V), Mastercard (...",0.0,0.0,0.0,True
935,2023-07-18 00:00:00+00:00,3 Warren Buffett Stocks That Everyone Should Own,Let's take a page from the Oracle of Omaha's i...,0.0,0.0,0.0,True
936,2023-07-17 00:00:00+00:00,MasterCard (MA) Stock Sinks As Market Gains: W...,MasterCard (MA) closed the most recent trading...,0.0,0.0,0.0,True
937,2023-07-17 00:00:00+00:00,Mastercard (MA) & DTS Unite to Minimize Digita...,Mastercard (MA) collaborates with DTS to provi...,0.0,0.0,0.0,True

In [38]:
type(news_values2['date'].loc[0])

pandas._libs.tslibs.timestamps.Timestamp