In [1]:
import pandas as pd

In [13]:
from transformers import BertTokenizer, BertForSequenceClassification, pipeline

In [4]:
news_values = pd.read_csv('../data/csv/final.csv')

In [5]:

news_values

,date,title,real_news,ma,axp,cof,es_ingles
0,2026-03-04T22:39:00Z,Bitget Wallet amplía su tarjeta cripto sin com...,Bitget Wallet has launched a crypto payment ca...,0.0,0.0,0.0,True
1,2026-03-04T17:28:00Z,Meta Is Bringing Back Stablecoin Payments—This...,Meta plans to launch a stablecoin with a third...,0.0,0.0,0.0,True
2,2026-03-04T16:01:00Z,SoFi Gains Traction as Mastercard Deal Brings ...,SoFi Technologies announced an enhanced partne...,1.0,0.0,0.0,True
3,2026-03-04T02:44:00Z,Bitget Wallet Expands Zero-Fee Crypto Card in ...,Bitget Wallet has launched a cryptocurrency pa...,0.0,0.0,0.0,True
4,2026-03-03T22:20:48Z,"Stock Market Today, March 3: SoFi Technologies...",SoFi Technologies rose 1.22% to $18.61 on Marc...,1.0,0.0,0.0,True
...,...,...,...,...,...,...,...
933,2023-07-18T15:58:00Z,Mastercard (MA) & Geidea Partner to Drive Paym...,Mastercard (MA) collaborates with Geidea to pr...,0.0,0.0,0.0,True
934,2023-07-18T10:40:00Z,3 Payment Stocks Gaining From Improving Consum...,"Payment processors like Visa (V), Mastercard (...",0.0,0.0,0.0,True
935,2023-07-18T09:33:00Z,3 Warren Buffett Stocks That Everyone Should Own,Let's take a page from the Oracle of Omaha's i...,0.0,0.0,0.0,True
936,2023-07-17T21:45:18Z,MasterCard (MA) Stock Sinks As Market Gains: W...,MasterCard (MA) closed the most recent trading...,0.0,0.0,0.0,True
937,2023-07-17T17:12:00Z,Mastercard (MA) & DTS Unite to Minimize Digita...,Mastercard (MA) collaborates with DTS to provi...,0.0,0.0,0.0,True

In [14]:
nlp = pipeline("sentiment-analysis", model="ProsusAI/finbert")

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: ProsusAI/finbert
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [18]:
value = nlp( f'Regarding Mastercard: {news_values.loc[0]['real_news']}' )

In [19]:
value

[{'label': 'neutral', 'score': 0.7797413468360901}]

In [ ]:
news_values.loc[0]['real_news']

'Bitget Wallet has launched a crypto payment card in Latin America in partnership with Immersve, enabling users to spend stablecoins (USDC) directly from self-custody wallets with automatic USD conversion. The card offers no reload, monthly, or inactivity fees, with full reimbursement of exchange and conversion fees within monthly limits, providing approximately 1.7% savings compared to traditional cards. The card is available across 11 Latin American countries and works with Apple Pay and Google Pay at over 150 million Mastercard-accepting merchants worldwide.'

In [3]:
data1 = pd.read_csv('../data/csv/final.csv')

In [4]:
data1

,date,title,real_news,ma,axp,cof,es_ingles,news_score
0,2026-03-04 00:00:00+00:00,Bitget Wallet amplía su tarjeta cripto sin com...,Bitget Wallet has launched a crypto payment ca...,0.0,0.0,0.0,True,0.000000
1,2026-03-04 00:00:00+00:00,Meta Is Bringing Back Stablecoin Payments—This...,Meta plans to launch a stablecoin with a third...,0.0,0.0,0.0,True,0.942217
2,2026-03-04 00:00:00+00:00,SoFi Gains Traction as Mastercard Deal Brings ...,SoFi Technologies announced an enhanced partne...,1.0,0.0,0.0,True,0.931969
3,2026-03-04 00:00:00+00:00,Bitget Wallet Expands Zero-Fee Crypto Card in ...,Bitget Wallet has launched a cryptocurrency pa...,0.0,0.0,0.0,True,0.000000
4,2026-03-03 00:00:00+00:00,"Stock Market Today, March 3: SoFi Technologies...",SoFi Technologies rose 1.22% to $18.61 on Marc...,1.0,0.0,0.0,True,-0.965844
...,...,...,...,...,...,...,...,...
935,2023-07-18 00:00:00+00:00,Mastercard (MA) & Geidea Partner to Drive Paym...,Mastercard (MA) collaborates with Geidea to pr...,0.0,0.0,0.0,True,0.909683
936,2023-07-18 00:00:00+00:00,3 Payment Stocks Gaining From Improving Consum...,"Payment processors like Visa (V), Mastercard (...",0.0,0.0,0.0,True,0.930809
937,2023-07-18 00:00:00+00:00,3 Warren Buffett Stocks That Everyone Should Own,Let's take a page from the Oracle of Omaha's i...,0.0,0.0,0.0,True,0.000000
938,2023-07-17 00:00:00+00:00,MasterCard (MA) Stock Sinks As Market Gains: W...,MasterCard (MA) closed the most recent trading...,0.0,0.0,0.0,True,-0.547946
939,2023-07-17 00:00:00+00:00,Mastercard (MA) & DTS Unite to Minimize Digita...,Mastercard (MA) collaborates with DTS to provi...,0.0,0.0,0.0,True,0.906971

In [17]:
data1.loc[ data1['news_score'] < 0 ]

,date,title,real_news,ma,axp,cof,es_ingles,news_score
4,2026-03-03 00:00:00+00:00,"Stock Market Today, March 3: SoFi Technologies...",SoFi Technologies rose 1.22% to $18.61 on Marc...,1.0,0.0,0.0,True,-0.965844
5,2026-03-03 00:00:00+00:00,The Financial Sector Is Under Pressure,The financial sector is underperforming the S&...,-1.0,0.0,0.0,True,-0.971502
8,2026-02-22 00:00:00+00:00,2 Financial Stocks Poised for a Comeback in 2026,"Visa and Moody's, both Warren Buffett holdings...",0.0,0.0,0.0,True,-0.929820
10,2026-02-18 00:00:00+00:00,The Fed's Next Move: Why Traders Are Piling In...,"Traders are increasingly investing in FAS, a l...",0.0,0.0,0.0,True,-0.769720
12,2026-02-17 00:00:00+00:00,"Cloudflare, Mastercard To Develop Cybersecurit...",Cloudflare and Mastercard announced a strategi...,1.0,0.0,0.0,True,-0.950603
...,...,...,...,...,...,...,...,...
913,2023-07-27 00:00:00+00:00,We'll Do It Live,"Hold onto your coffee cups, 'cause we're kicki...",0.0,0.0,0.0,True,-0.965496
915,2023-07-27 00:00:00+00:00,Mastercard moves to stop cannabis purchases wi...,Mastercard Inc. has demanded that U.S. financi...,0.0,0.0,0.0,True,-0.962356
917,2023-07-27 00:00:00+00:00,"Oil will hit $90 a barrel, says Bank of Americ...",Rising energy costs may inflame inflationary p...,0.0,0.0,0.0,True,-0.948966
934,2023-07-19 00:00:00+00:00,2 Dividend Stocks That Doubled Their Payouts i...,There's no reason to expect these companies to...,0.0,0.0,0.0,True,-0.458641
938,2023-07-17 00:00:00+00:00,MasterCard (MA) Stock Sinks As Market Gains: W...,MasterCard (MA) closed the most recent trading...,0.0,0.0,0.0,True,-0.547946

In [10]:
data1.loc[4]['real_news']

"SoFi Technologies rose 1.22% to $18.61 on March 3, 2026, driven by a deepened stablecoin partnership with Mastercard and CEO Anthony Noto's $1 million insider share purchase. Under the partnership, SoFi's stablecoin (SoFiUSD) will be offered as a settlement option across Mastercard's payment network. The broader market declined, with the S&P 500 falling 0.94% and Nasdaq dropping 1.02%."

In [15]:
value2 = nlp( f'Regarding Mastercard: {data1.loc[4]['real_news']}' )

In [16]:
value2

[{'label': 'negative', 'score': 0.9658439755439758}]

In [18]:
#es una noticia positiva... finbert es muy generico, voy a usar el multiplicador con la puntuacion de la api de noticias...

In [2]:
value3 = pd.read_csv('../data/csv/final.csv')

In [3]:
value3

,date,title,real_news,ma,axp,cof,es_ingles,news_score
0,2026-03-04 00:00:00+00:00,Bitget Wallet amplía su tarjeta cripto sin com...,Bitget Wallet has launched a crypto payment ca...,0.0,0.0,0.0,True,0.000000
1,2026-03-04 00:00:00+00:00,Meta Is Bringing Back Stablecoin Payments—This...,Meta plans to launch a stablecoin with a third...,0.0,0.0,0.0,True,0.942217
2,2026-03-04 00:00:00+00:00,SoFi Gains Traction as Mastercard Deal Brings ...,SoFi Technologies announced an enhanced partne...,1.0,0.0,0.0,True,0.931969
3,2026-03-04 00:00:00+00:00,Bitget Wallet Expands Zero-Fee Crypto Card in ...,Bitget Wallet has launched a cryptocurrency pa...,0.0,0.0,0.0,True,0.000000
4,2026-03-03 00:00:00+00:00,"Stock Market Today, March 3: SoFi Technologies...",SoFi Technologies rose 1.22% to $18.61 on Marc...,1.0,0.0,0.0,True,0.965844
...,...,...,...,...,...,...,...,...
935,2023-07-18 00:00:00+00:00,Mastercard (MA) & Geidea Partner to Drive Paym...,Mastercard (MA) collaborates with Geidea to pr...,0.0,0.0,0.0,True,0.909683
936,2023-07-18 00:00:00+00:00,3 Payment Stocks Gaining From Improving Consum...,"Payment processors like Visa (V), Mastercard (...",0.0,0.0,0.0,True,0.930809
937,2023-07-18 00:00:00+00:00,3 Warren Buffett Stocks That Everyone Should Own,Let's take a page from the Oracle of Omaha's i...,0.0,0.0,0.0,True,0.000000
938,2023-07-17 00:00:00+00:00,MasterCard (MA) Stock Sinks As Market Gains: W...,MasterCard (MA) closed the most recent trading...,0.0,0.0,0.0,True,-0.547946
939,2023-07-17 00:00:00+00:00,Mastercard (MA) & DTS Unite to Minimize Digita...,Mastercard (MA) collaborates with DTS to provi...,0.0,0.0,0.0,True,0.906971

In [6]:
value3.loc[938]['real_news']

'MasterCard (MA) closed the most recent trading day at $402.20, moving -0.08% from the previous trading session.'