In [1]:
import pandas as pd
import datetime

In [3]:
data = pd.read_csv("./csv/datos_2023-07-10_a_2026-02-04_con_noticias.csv")

In [4]:
data

,Unnamed: 0,date,title,real_news,ma,axp,cof
0,0,2026-02-08,Visa and Mastercard Execs Recently Dismissed S...,Visa and Mastercard executives have dismissed ...,negative,NaN,NaN
1,1,2026-02-04,Behavioral Biometrics Market to Reach US$ 18.3...,The global behavioral biometrics market is pro...,positive,NaN,NaN
2,2,2026-02-03,Here's Why Mastercard Stock Is Still a Buy Des...,Despite regulatory headwinds from a proposed 1...,positive,negative,negative
3,3,2026-02-02,Why a 2.1% Portfolio Shift Targets a New ETF W...,Capital Planning LLC initiated a new position ...,positive,NaN,NaN
4,4,2026-02-01,Affiance Financial Bets $43 Million on Chuck A...,Affiance Financial initiated a new $43 million...,positive,NaN,NaN
...,...,...,...,...,...,...,...
936,936,2023-07-13,FIS or MA: Which Is the Better Value Stock Rig...,FIS vs. MA: Which Stock Is the Better Value Op...,NaN,NaN,NaN
937,937,2023-07-13,Netflix To Rally More Than 11%? Here Are 10 Ot...,Mizuho boosted the price target for Gulfport ...,NaN,NaN,NaN
938,938,2023-07-13,1 Spectacular Warren Buffett Dividend Stock Th...,Warren Buffett is not against investing in div...,NaN,NaN,NaN
939,939,2023-07-11,MasterCard (MA) Outpaces Stock Market Gains: W...,"In the latest trading session, MasterCard (MA)...",NaN,NaN,NaN
940,940,2023-07-11,Mastercard (MA) & JazzCash to Speed Up Digitiz...,Mastercard (MA) partners with JazzCash to driv...,NaN,NaN,NaN

In [5]:
test = data.drop("Unnamed: 0", axis=1)

In [6]:
test = test.set_index("date")

In [7]:
test.to_csv("./csv/datos_2023-07-10_a_2026-02-04_con_noticias.csv")

In [ ]:
#corrijo esa columna arriba pq me olvide antes de poner .csv en nombre de archivo, y tampoco elimine el index.

In [27]:
#ahora si vamos con buscar las fechas faltantes, y elimiar noticias que no esten en ingles.

In [28]:
pip install langdetect

Collecting langdetect
  Downloading langdetect-1.0.9.tar.gz (981 kB)
     ---------------------------------------- 0.0/981.5 kB ? eta -:--:--
     ------------------------------------- 981.5/981.5 kB 34.3 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: six in c:\users\usuario\appdata\local\programs\python\python313\lib\site-packages (from langdetect) (1.17.0)
Building wheels for collected packages: langdetect
  Building wheel for langdetect (setup.py): started
  Building wheel for langdetect (setup.py): finished with status 'done'
  Created wheel for langdetect: filename=langdetect-1.0.9-py3-none-any.whl size=993363 sha256=b9bf2f950e22ed8c794f3ec6e047b45b43fb8373640fc1796639dbe69bf62962
  Stored in directory: c:\users\usuario\appdata\local\pip\cache\wheels\eb\87\25\2dddf1c94e1786054e25022ec5530bfed52bad86d882999c48
Successfully built langdetect
Installing collected packages: langdetect
Successfully installed langdetect-1.0.9
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [34]:
data.reset_index()

,index,date,title,ma,axp,cof
0,0,2026-02-04,Behavioral Biometrics Market to Reach US$ 18.3...,positive,NaN,NaN
1,1,2026-02-03,Here's Why Mastercard Stock Is Still a Buy Des...,positive,negative,negative
2,2,2026-02-02,Why a 2.1% Portfolio Shift Targets a New ETF W...,positive,NaN,NaN
3,3,2026-02-01,Affiance Financial Bets $43 Million on Chuck A...,positive,NaN,NaN
4,4,2026-02-01,This Low-Cost Dividend ETF Can Be a Surprising...,positive,NaN,NaN
...,...,...,...,...,...,...
945,945,2023-07-13,1 Spectacular Warren Buffett Dividend Stock Th...,NaN,NaN,NaN
946,946,2023-07-11,MasterCard (MA) Outpaces Stock Market Gains: W...,NaN,NaN,NaN
947,947,2023-07-11,Mastercard (MA) & JazzCash to Speed Up Digitiz...,NaN,NaN,NaN
948,948,2023-07-11,This 6.2% AI Dividend Pays Us Every Month,NaN,NaN,NaN
949,949,2023-07-10,Mastercard (MA) and DET Launch Unique Digital ...,NaN,NaN,NaN

In [12]:
from langdetect import detect

In [10]:
prueba_translate = detect(data.loc[data.index[0]]["title"])

In [11]:
prueba_translate

'en'

In [13]:
def es_ingles(text):
    if detect(text) == "en":
        return True
    else:
        return False

In [28]:
data2 = test.copy()

In [74]:
data2

,title,real_news,ma,axp,cof,es_ingles
date,,,,,,
2026-02-08,Visa and Mastercard Execs Recently Dismissed S...,Visa and Mastercard executives have dismissed ...,negative,NaN,NaN,True
2026-02-04,Behavioral Biometrics Market to Reach US$ 18.3...,The global behavioral biometrics market is pro...,positive,NaN,NaN,True
2026-02-03,Here's Why Mastercard Stock Is Still a Buy Des...,Despite regulatory headwinds from a proposed 1...,positive,negative,negative,True
2026-02-02,Why a 2.1% Portfolio Shift Targets a New ETF W...,Capital Planning LLC initiated a new position ...,positive,NaN,NaN,True
2026-02-01,Affiance Financial Bets $43 Million on Chuck A...,Affiance Financial initiated a new $43 million...,positive,NaN,NaN,True
...,...,...,...,...,...,...
2023-07-13,FIS or MA: Which Is the Better Value Stock Rig...,FIS vs. MA: Which Stock Is the Better Value Op...,NaN,NaN,NaN,True
2023-07-13,Netflix To Rally More Than 11%? Here Are 10 Ot...,Mizuho boosted the price target for Gulfport ...,NaN,NaN,NaN,True
2023-07-13,1 Spectacular Warren Buffett Dividend Stock Th...,Warren Buffett is not against investing in div...,NaN,NaN,NaN,True
2023-07-11,MasterCard (MA) Outpaces Stock Market Gains: W...,"In the latest trading session, MasterCard (MA)...",NaN,NaN,NaN,True
2023-07-11,Mastercard (MA) & JazzCash to Speed Up Digitiz...,Mastercard (MA) partners with JazzCash to driv...,NaN,NaN,NaN,True

In [30]:
data2["es_ingles"] = data2.title.apply(es_ingles)

In [32]:
notiocias_no_ingles = data2.loc[data2.es_ingles != True]

In [49]:
notiocias_no_ingles

,title,real_news,ma,axp,cof,es_ingles
date,,,,,,
2025-11-03,Ferrari Order Strength and Mastercard Earnings...,Ferrari and Mastercard demonstrate strong perf...,positive,NaN,NaN,True
2025-09-12,Měsíční zpráva: Bitget Futures se zařadila mez...,"Bitget, a leading cryptocurrency exchange, rep...",positive,NaN,NaN,False
2025-09-11,月度报告重点呈现：Bitget 期货 ETH 交易量跻身前三，再创历史新高,Bitget released its August 2025 Transparency R...,positive,NaN,NaN,False
2025-09-11,Pasaran Hadapan Bitget Menduduki #3 Teratas un...,Bitget achieved significant milestones in Augu...,positive,NaN,NaN,False
2025-09-11,在 ETH 屢創新高之際，Bitget 期貨強勢躍居全球前三，每月報告重點解構,"Bitget, a leading cryptocurrency exchange, rep...",positive,NaN,NaN,False
2025-09-11,Bitget Futures fica entre as três principais e...,Bitget reported record derivatives trading vol...,positive,NaN,NaN,False
2025-09-11,Los futuros de Bitget se ubican entre los 3 pr...,Bitget reported record trading volumes in Augu...,positive,NaN,NaN,False
2025-09-11,"Bitget 선물, ETH 부문 글로벌 Top 3 진입… 신규 사상 최고치 속 월간...",Bitget released its August 2025 Transparency R...,positive,NaN,NaN,False
2025-08-18,Červencová zpráva Bitget uvádí čistý příjem 46...,Cryptocurrency exchange Bitget reported $461.3...,positive,NaN,NaN,False
2025-08-18,Der Juli-Bericht von Bitget weist Nettozuflüss...,"Bitget reported strong growth in July, with $4...",neutral,NaN,NaN,False
2025-08-03,Bitget Membuka Pelaburan Pasif dengan Fungsi A...,Bitget introduces a new Recurring Buy feature ...,neutral,NaN,NaN,False
2025-08-03,Bitget propose l’achat automatique pour permet...,Bitget introduces a new Recurring Buy feature ...,neutral,NaN,NaN,False
2025-08-03,Bitget מאפשרת השקעה פסיבית פתוחה באופן אוטומטי...,Bitget introduces an automated cryptocurrency ...,neutral,NaN,NaN,False
2025-08-03,ビットゲット (Bitget)、年間最大30％のリターンを可能にする自動購入機能を提供し、パ...,Bitget introduces a new 'Recurring Buy' featur...,neutral,NaN,NaN,False
2025-08-03,Bitget 以自動購買功能啟動被動投資，年度回報率高達 30%,Bitget introduces a new recurring buy feature ...,neutral,NaN,NaN,False
2025-08-03,"Bitget, 자동 매수 기능 도입으로 연간 최대 30% 수익률 기대되는 패시브 투...",Bitget introduces 'Recurring Buy' feature allo...,neutral,NaN,NaN,False
2025-08-03,Bitget possibilita a abertura de investimentos...,Bitget introduces a new Recurring Buy feature ...,neutral,NaN,NaN,False
2025-07-21,"Zpráva Bitget Wallet odhaluje, že oblíbenými o...","A Bitget Wallet survey of 4,599 users reveals ...",positive,NaN,NaN,False
2025-07-08,Bitget Wallet 與 Mastercard 及 Immersve 攜手推出零手續費...,Bitget Wallet collaborates with Mastercard and...,positive,NaN,NaN,False
2025-07-08,Bitget Wallet משתפת פעולה עם Mastercard ו-Imme...,"Bitget Wallet, Mastercard, and Immersve launch...",positive,NaN,NaN,False
2025-07-08,Bitget Wallet Bekerjasama dengan Mastercard da...,Bitget Wallet collaborates with Mastercard and...,positive,NaN,NaN,False
2025-07-08,Bitget Wallet se asocia con Mastercard e Immer...,Bitget Wallet collaborates with Mastercard and...,positive,NaN,NaN,False
2025-07-08,Bitget Wallet 与 Mastercard 和 Immersve 合作推出零手续费...,Bitget Wallet collaborates with Mastercard and...,positive,NaN,NaN,False
2025-07-08,"Bitget Wallet, 마스터카드 및 Immersve와 제휴하여 수수료 없는 암...",Bitget Wallet partnered with Mastercard and Im...,positive,NaN,NaN,False
2025-07-08,ビットゲットウォレット (Bitget Wallet)、マスターカード (Mastercar...,Bitget Wallet partners with Mastercard and Imm...,positive,NaN,NaN,False
2025-07-08,Bitget Wallet firma parceria com a Mastercard ...,Bitget Wallet has partnered with Mastercard an...,positive,NaN,NaN,False
2025-05-28,Partenariat entre ila Bank et Mastercard visan...,"ila Bank, a subsidiary of Bank ABC, has partne...",positive,NaN,NaN,False
2025-05-28,ila Bank geht Partnerschaft mit Mastercard ein...,"ila Bank, powered by Bank ABC, has partnered w...",positive,NaN,NaN,False
2024-12-09,Best Stocks to Buy Before 2025: Visa Stock vs....,The Motley Fool is a financial services compan...,positive,NaN,NaN,False
2024-10-25,Is Visa Stock a Buy?,Visa is facing an antitrust lawsuit from the U...,neutral,NaN,NaN,False
2024-08-18,"Visa Stock: Buy, Sell, or Hold?",Visa's stock has underperformed the S&P 500 th...,neutral,NaN,NaN,False
2024-08-15,Annonce des lauréats internationaux de la 21e ...,The 21st edition of the International Business...,positive,NaN,NaN,False
2024-05-15,2 Warren Buffett Stocks to Hold Forever,These Buffett-approved businesses can grow you...,NaN,NaN,NaN,True
2024-05-10,Baron Durable Advantage Fund Q1 2024 Sharehold...,Baron Durable Advantage Fund (Inst.) gained 10...,NaN,NaN,NaN,False
2024-05-03,"Tesla, Boeing, Visa: Big Names Worth Talking A...",Tesla and its robotaxi ambitions lead the show.,NaN,NaN,NaN,False
2024-04-07,Will Visa Be a Trillion-Dollar Stock by 2035?,There is one big reason to believe Visa will b...,NaN,NaN,NaN,False
2024-03-01,Is Visa Stock a Buy?,Visa has delivered market-beating returns sinc...,NaN,NaN,NaN,False
2024-01-19,Is Visa Stock a Buy?,Investors will struggle to find reasons agains...,NaN,NaN,NaN,False
2024-01-17,"ADP Analyst Upgrades Stock Before Q2 Earnings,...",Shares of Automatic Data Processing Inc (NASDA...,NaN,NaN,NaN,True
2023-12-18,Mastercard Vs. Visa: Which One Is A Better Buy?,Mastercard and Visa offer low dividend yields ...,NaN,NaN,NaN,False
2023-12-09,3 Warren Buffett Stocks to Buy Hand Over Fist ...,The credit card companies have a massive upsid...,NaN,NaN,NaN,False
2023-09-21,"Mastercard (MA), AEGF to Digitize India's Agri...",Mastercard (MA) teams up with AEGF to combine ...,NaN,NaN,NaN,False
2023-08-12,3 Best Dividend Stocks for Retirement,Here are three dividend-paying stocks that can...,NaN,NaN,NaN,False
2023-07-13,Mastercard (MA) & Vodafone to Drive Financial ...,Mastercard (MA) partners with Vodafone to driv...,NaN,NaN,NaN,False

In [42]:
noticias_prueba2 = pd.DataFrame(notiocias_no_ingles)

In [45]:
noticias_prueba2["es_ingles"] = noticias_prueba2.title.apply(es_ingles)

In [48]:
noticias_prueba2

,title,real_news,ma,axp,cof,es_ingles
date,,,,,,
2025-11-03,Ferrari Order Strength and Mastercard Earnings...,Ferrari and Mastercard demonstrate strong perf...,positive,NaN,NaN,False
2025-09-12,Měsíční zpráva: Bitget Futures se zařadila mez...,"Bitget, a leading cryptocurrency exchange, rep...",positive,NaN,NaN,False
2025-09-11,月度报告重点呈现：Bitget 期货 ETH 交易量跻身前三，再创历史新高,Bitget released its August 2025 Transparency R...,positive,NaN,NaN,False
2025-09-11,Pasaran Hadapan Bitget Menduduki #3 Teratas un...,Bitget achieved significant milestones in Augu...,positive,NaN,NaN,False
2025-09-11,在 ETH 屢創新高之際，Bitget 期貨強勢躍居全球前三，每月報告重點解構,"Bitget, a leading cryptocurrency exchange, rep...",positive,NaN,NaN,False
2025-09-11,Bitget Futures fica entre as três principais e...,Bitget reported record derivatives trading vol...,positive,NaN,NaN,False
2025-09-11,Los futuros de Bitget se ubican entre los 3 pr...,Bitget reported record trading volumes in Augu...,positive,NaN,NaN,False
2025-09-11,"Bitget 선물, ETH 부문 글로벌 Top 3 진입… 신규 사상 최고치 속 월간...",Bitget released its August 2025 Transparency R...,positive,NaN,NaN,False
2025-08-18,Červencová zpráva Bitget uvádí čistý příjem 46...,Cryptocurrency exchange Bitget reported $461.3...,positive,NaN,NaN,False
2025-08-18,Der Juli-Bericht von Bitget weist Nettozuflüss...,"Bitget reported strong growth in July, with $4...",neutral,NaN,NaN,False
2025-08-03,Bitget Membuka Pelaburan Pasif dengan Fungsi A...,Bitget introduces a new Recurring Buy feature ...,neutral,NaN,NaN,False
2025-08-03,Bitget propose l’achat automatique pour permet...,Bitget introduces a new Recurring Buy feature ...,neutral,NaN,NaN,False
2025-08-03,Bitget מאפשרת השקעה פסיבית פתוחה באופן אוטומטי...,Bitget introduces an automated cryptocurrency ...,neutral,NaN,NaN,False
2025-08-03,ビットゲット (Bitget)、年間最大30％のリターンを可能にする自動購入機能を提供し、パ...,Bitget introduces a new 'Recurring Buy' featur...,neutral,NaN,NaN,False
2025-08-03,Bitget 以自動購買功能啟動被動投資，年度回報率高達 30%,Bitget introduces a new recurring buy feature ...,neutral,NaN,NaN,False
2025-08-03,"Bitget, 자동 매수 기능 도입으로 연간 최대 30% 수익률 기대되는 패시브 투...",Bitget introduces 'Recurring Buy' feature allo...,neutral,NaN,NaN,False
2025-08-03,Bitget possibilita a abertura de investimentos...,Bitget introduces a new Recurring Buy feature ...,neutral,NaN,NaN,False
2025-07-21,"Zpráva Bitget Wallet odhaluje, že oblíbenými o...","A Bitget Wallet survey of 4,599 users reveals ...",positive,NaN,NaN,False
2025-07-08,Bitget Wallet 與 Mastercard 及 Immersve 攜手推出零手續費...,Bitget Wallet collaborates with Mastercard and...,positive,NaN,NaN,False
2025-07-08,Bitget Wallet משתפת פעולה עם Mastercard ו-Imme...,"Bitget Wallet, Mastercard, and Immersve launch...",positive,NaN,NaN,False
2025-07-08,Bitget Wallet Bekerjasama dengan Mastercard da...,Bitget Wallet collaborates with Mastercard and...,positive,NaN,NaN,False
2025-07-08,Bitget Wallet se asocia con Mastercard e Immer...,Bitget Wallet collaborates with Mastercard and...,positive,NaN,NaN,False
2025-07-08,Bitget Wallet 与 Mastercard 和 Immersve 合作推出零手续费...,Bitget Wallet collaborates with Mastercard and...,positive,NaN,NaN,False
2025-07-08,"Bitget Wallet, 마스터카드 및 Immersve와 제휴하여 수수료 없는 암...",Bitget Wallet partnered with Mastercard and Im...,positive,NaN,NaN,False
2025-07-08,ビットゲットウォレット (Bitget Wallet)、マスターカード (Mastercar...,Bitget Wallet partners with Mastercard and Imm...,positive,NaN,NaN,False
2025-07-08,Bitget Wallet firma parceria com a Mastercard ...,Bitget Wallet has partnered with Mastercard an...,positive,NaN,NaN,False
2025-05-28,Partenariat entre ila Bank et Mastercard visan...,"ila Bank, a subsidiary of Bank ABC, has partne...",positive,NaN,NaN,False
2025-05-28,ila Bank geht Partnerschaft mit Mastercard ein...,"ila Bank, powered by Bank ABC, has partnered w...",positive,NaN,NaN,False
2024-12-09,Best Stocks to Buy Before 2025: Visa Stock vs....,The Motley Fool is a financial services compan...,positive,NaN,NaN,False
2024-10-25,Is Visa Stock a Buy?,Visa is facing an antitrust lawsuit from the U...,neutral,NaN,NaN,True
2024-08-18,"Visa Stock: Buy, Sell, or Hold?",Visa's stock has underperformed the S&P 500 th...,neutral,NaN,NaN,False
2024-08-15,Annonce des lauréats internationaux de la 21e ...,The 21st edition of the International Business...,positive,NaN,NaN,False
2024-05-15,2 Warren Buffett Stocks to Hold Forever,These Buffett-approved businesses can grow you...,NaN,NaN,NaN,True
2024-05-10,Baron Durable Advantage Fund Q1 2024 Sharehold...,Baron Durable Advantage Fund (Inst.) gained 10...,NaN,NaN,NaN,False
2024-05-03,"Tesla, Boeing, Visa: Big Names Worth Talking A...",Tesla and its robotaxi ambitions lead the show.,NaN,NaN,NaN,True
2024-04-07,Will Visa Be a Trillion-Dollar Stock by 2035?,There is one big reason to believe Visa will b...,NaN,NaN,NaN,False
2024-03-01,Is Visa Stock a Buy?,Visa has delivered market-beating returns sinc...,NaN,NaN,NaN,False
2024-01-19,Is Visa Stock a Buy?,Investors will struggle to find reasons agains...,NaN,NaN,NaN,False
2024-01-17,"ADP Analyst Upgrades Stock Before Q2 Earnings,...",Shares of Automatic Data Processing Inc (NASDA...,NaN,NaN,NaN,False
2023-12-18,Mastercard Vs. Visa: Which One Is A Better Buy?,Mastercard and Visa offer low dividend yields ...,NaN,NaN,NaN,True
2023-12-09,3 Warren Buffett Stocks to Buy Hand Over Fist ...,The credit card companies have a massive upsid...,NaN,NaN,NaN,False
2023-09-21,"Mastercard (MA), AEGF to Digitize India's Agri...",Mastercard (MA) teams up with AEGF to combine ...,NaN,NaN,NaN,False
2023-08-12,3 Best Dividend Stocks for Retirement,Here are three dividend-paying stocks that can...,NaN,NaN,NaN,False
2023-07-13,Mastercard (MA) & Vodafone to Drive Financial ...,Mastercard (MA) partners with Vodafone to driv...,NaN,NaN,NaN,False

In [82]:
noticias_falso_negativo_ingles = noticias_prueba2.iloc[27:]

In [79]:
noticias_falso_negativo_ingles = noticias_falso_negativo_ingles.loc[noticias_falso_negativo_ingles.title != 'Annonce des lauréats internationaux de la 21e\xa0édition du programme de récompense International Business Awards® des Stevie® Awards']

In [81]:
len(noticias_falso_negativo_ingles)

16

In [59]:
data2 = data2.loc[data2["es_ingles"] == True]

In [84]:
data2

,title,real_news,ma,axp,cof,es_ingles
date,,,,,,
2026-02-08,Visa and Mastercard Execs Recently Dismissed S...,Visa and Mastercard executives have dismissed ...,negative,NaN,NaN,True
2026-02-04,Behavioral Biometrics Market to Reach US$ 18.3...,The global behavioral biometrics market is pro...,positive,NaN,NaN,True
2026-02-03,Here's Why Mastercard Stock Is Still a Buy Des...,Despite regulatory headwinds from a proposed 1...,positive,negative,negative,True
2026-02-02,Why a 2.1% Portfolio Shift Targets a New ETF W...,Capital Planning LLC initiated a new position ...,positive,NaN,NaN,True
2026-02-01,Affiance Financial Bets $43 Million on Chuck A...,Affiance Financial initiated a new $43 million...,positive,NaN,NaN,True
...,...,...,...,...,...,...
2023-07-13,FIS or MA: Which Is the Better Value Stock Rig...,FIS vs. MA: Which Stock Is the Better Value Op...,NaN,NaN,NaN,True
2023-07-13,Netflix To Rally More Than 11%? Here Are 10 Ot...,Mizuho boosted the price target for Gulfport ...,NaN,NaN,NaN,True
2023-07-13,1 Spectacular Warren Buffett Dividend Stock Th...,Warren Buffett is not against investing in div...,NaN,NaN,NaN,True
2023-07-11,MasterCard (MA) Outpaces Stock Market Gains: W...,"In the latest trading session, MasterCard (MA)...",NaN,NaN,NaN,True
2023-07-11,Mastercard (MA) & JazzCash to Speed Up Digitiz...,Mastercard (MA) partners with JazzCash to driv...,NaN,NaN,NaN,True

In [85]:
data_final = pd.concat([data2, noticias_falso_negativo_ingles])

In [86]:
data_final

,title,real_news,ma,axp,cof,es_ingles
date,,,,,,
2026-02-08,Visa and Mastercard Execs Recently Dismissed S...,Visa and Mastercard executives have dismissed ...,negative,NaN,NaN,True
2026-02-04,Behavioral Biometrics Market to Reach US$ 18.3...,The global behavioral biometrics market is pro...,positive,NaN,NaN,True
2026-02-03,Here's Why Mastercard Stock Is Still a Buy Des...,Despite regulatory headwinds from a proposed 1...,positive,negative,negative,True
2026-02-02,Why a 2.1% Portfolio Shift Targets a New ETF W...,Capital Planning LLC initiated a new position ...,positive,NaN,NaN,True
2026-02-01,Affiance Financial Bets $43 Million on Chuck A...,Affiance Financial initiated a new $43 million...,positive,NaN,NaN,True
...,...,...,...,...,...,...
2023-12-18,Mastercard Vs. Visa: Which One Is A Better Buy?,Mastercard and Visa offer low dividend yields ...,NaN,NaN,NaN,True
2023-12-09,3 Warren Buffett Stocks to Buy Hand Over Fist ...,The credit card companies have a massive upsid...,NaN,NaN,NaN,False
2023-09-21,"Mastercard (MA), AEGF to Digitize India's Agri...",Mastercard (MA) teams up with AEGF to combine ...,NaN,NaN,NaN,False
2023-08-12,3 Best Dividend Stocks for Retirement,Here are three dividend-paying stocks that can...,NaN,NaN,NaN,False
2023-07-13,Mastercard (MA) & Vodafone to Drive Financial ...,Mastercard (MA) partners with Vodafone to driv...,NaN,NaN,NaN,False

In [89]:
data_final.sort_index(ascending= True, inplace= True)

In [90]:
data_final.drop(columns="es_ingles", inplace=True)

In [91]:
data_final

,title,real_news,ma,axp,cof
date,,,,,
2023-07-11,MasterCard (MA) Outpaces Stock Market Gains: W...,"In the latest trading session, MasterCard (MA)...",NaN,NaN,NaN
2023-07-11,Mastercard (MA) & JazzCash to Speed Up Digitiz...,Mastercard (MA) partners with JazzCash to driv...,NaN,NaN,NaN
2023-07-13,Mastercard (MA) & Vodafone to Drive Financial ...,Mastercard (MA) partners with Vodafone to driv...,NaN,NaN,NaN
2023-07-13,FIS or MA: Which Is the Better Value Stock Rig...,FIS vs. MA: Which Stock Is the Better Value Op...,NaN,NaN,NaN
2023-07-13,1 Spectacular Warren Buffett Dividend Stock Th...,Warren Buffett is not against investing in div...,NaN,NaN,NaN
...,...,...,...,...,...
2026-02-01,Affiance Financial Bets $43 Million on Chuck A...,Affiance Financial initiated a new $43 million...,positive,NaN,NaN
2026-02-02,Why a 2.1% Portfolio Shift Targets a New ETF W...,Capital Planning LLC initiated a new position ...,positive,NaN,NaN
2026-02-03,Here's Why Mastercard Stock Is Still a Buy Des...,Despite regulatory headwinds from a proposed 1...,positive,negative,negative
2026-02-04,Behavioral Biometrics Market to Reach US$ 18.3...,The global behavioral biometrics market is pro...,positive,NaN,NaN
2026-02-08,Visa and Mastercard Execs Recently Dismissed S...,Visa and Mastercard executives have dismissed ...,negative,NaN,NaN

In [92]:
data_final.to_csv("./csv/datos_2023-07-11_a_2026_02_08.csv")

In [21]:
rango_fechas = pd.date_range(start="2023-07-10",end="2026-02-04", freq="D")

In [207]:
data2.date[190]

Timestamp('2024-11-26 00:00:00')

In [209]:
fechas_faltantes = [str(date) for date in map(str, rango_fechas) if date not in map(str, data2.date)]

In [211]:
len(fechas_faltantes)

477

In [16]:
data= pd.read_csv("data/fechas_faltantes.csv")

In [17]:
data.rename(columns={"0":"date"}, inplace = True)
data.drop(columns="Unnamed: 0", inplace= True)

In [ ]:
pd.DataFrame(fechas_faltantes).to_csv("data/fechas_faltantes.csv")