In [27]:
import pandas as pd
import datetime
import numpy as np

In [39]:
data = pd.read_csv("../csv/scores_without_news.csv")

In [29]:
data.set_index("date", inplace=True)

In [40]:
data

           date        ma       axp       cof  news_score
0    2023-07-11         0         0         0    0.999471
1    2023-07-11         0         0         0    0.966982
2    2023-07-13         0         0         0    0.991283
3    2023-07-13         0         0         0    0.997588
4    2023-07-13         0         0         0    0.997954
..          ...       ...       ...       ...         ...
909  2026-02-01  positive         0         0    0.577380
910  2026-02-02  positive         0         0    0.999999
911  2026-02-03  positive  negative  negative    1.000000
912  2026-02-04  positive         0         0    0.999985
913  2026-02-08  negative         0         0    0.999999

[914 rows x 5 columns]

In [41]:
test = data.copy()

In [58]:
test.set_index("date", inplace = True)

In [43]:
def replace_values(cols,value, new_value):
    for col in cols:
        test[col] = test[col].replace(value, new_value)

In [44]:
replace_values(["ma","axp","cof"], "positive", 1)
replace_values(["ma","axp","cof"], "negative", -1)
replace_values(["ma","axp","cof"], "neutral", 0)

C:\Users\Usuario\AppData\Local\Temp\ipykernel_8708\2891747182.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  test[col] = test[col].replace(value, new_value)

In [56]:
test

          date   ma  axp  cof  news_score
0   2023-07-11  NaN  NaN  NaN    0.999471
1   2023-07-11  NaN  NaN  NaN    0.966982
2   2023-07-13  NaN  NaN  NaN    0.991283
3   2023-07-13  NaN  NaN  NaN    0.997588
4   2023-07-13  NaN  NaN  NaN    0.997954
..         ...  ...  ...  ...         ...
909 2026-02-01  1.0  NaN  NaN    0.577380
910 2026-02-02  1.0  NaN  NaN    0.999999
911 2026-02-03  1.0 -1.0 -1.0    1.000000
912 2026-02-04  1.0  NaN  NaN    0.999985
913 2026-02-08 -1.0  NaN  NaN    0.999999

[914 rows x 5 columns]

In [49]:
test["date"] = pd.to_datetime(test["date"])

In [60]:
test = test.resample("D").agg({
    "ma": "mean",
    "axp": "mean",
    "cof": "mean",
    "news_score":"mean"
})

In [61]:
test

             ma  axp  cof  news_score
date
2023-07-11  NaN  NaN  NaN    0.983227
2023-07-12  NaN  NaN  NaN         NaN
2023-07-13  NaN  NaN  NaN    0.996657
2023-07-14  NaN  NaN  NaN    0.967316
2023-07-15  NaN  NaN  NaN    0.995629
...         ...  ...  ...         ...
2026-02-04  1.0  NaN  NaN    0.999985
2026-02-05  NaN  NaN  NaN         NaN
2026-02-06  NaN  NaN  NaN         NaN
2026-02-07  NaN  NaN  NaN         NaN
2026-02-08 -1.0  NaN  NaN    0.999999

[944 rows x 4 columns]

In [67]:
test.loc[test.ma == 0.5]

             ma  axp  cof  news_score
date
2024-08-12  0.5  1.0  0.0    0.999999
2024-09-03  0.5  NaN  NaN    0.681876
2024-09-09  0.5  NaN  NaN    0.999340
2024-10-16  0.5  1.0  NaN    1.000000
2024-11-18  0.5  NaN  NaN    0.984129
2025-02-17  0.5  NaN  NaN    0.833271
2025-04-05  0.5  1.0  NaN    0.915089
2025-08-28  0.5  NaN  NaN    0.987062
2026-01-28  0.5 -1.0 -1.0    0.999999

In [69]:
data

           date        ma       axp       cof  news_score
0    2023-07-11         0         0         0    0.999471
1    2023-07-11         0         0         0    0.966982
2    2023-07-13         0         0         0    0.991283
3    2023-07-13         0         0         0    0.997588
4    2023-07-13         0         0         0    0.997954
..          ...       ...       ...       ...         ...
909  2026-02-01  positive         0         0    0.577380
910  2026-02-02  positive         0         0    0.999999
911  2026-02-03  positive  negative  negative    1.000000
912  2026-02-04  positive         0         0    0.999985
913  2026-02-08  negative         0         0    0.999999

[914 rows x 5 columns]

In [74]:
test = test.fillna(0)

In [75]:
test.loc[test["ma"] != 0]

             ma  axp  cof  news_score
date
2024-07-03  1.0  1.0  0.0    0.715408
2024-07-04  1.0  0.0  0.0    0.999905
2024-07-08 -1.0 -1.0 -1.0    0.999991
2024-07-12  1.0  0.0  0.0    0.996636
2024-07-15  1.0  0.0  0.0    0.822531
...         ...  ...  ...         ...
2026-02-01  1.0  0.0  0.0    0.788689
2026-02-02  1.0  0.0  0.0    0.999999
2026-02-03  1.0 -1.0 -1.0    1.000000
2026-02-04  1.0  0.0  0.0    0.999985
2026-02-08 -1.0  0.0  0.0    0.999999

[125 rows x 4 columns]

In [77]:
test.to_csv("../csv/datos_terminados.csv")