In [56]:
from transformers import BertTokenizer, BertForSequenceClassification, pipeline

In [57]:
import pandas as pd

In [60]:
data = pd.read_csv("../data/csv/datos_2023-07-11_a_2026_02_08.csv")

In [61]:
data

,date,title,real_news,ma,axp,cof
0,2023-07-11,MasterCard (MA) Outpaces Stock Market Gains: W...,"In the latest trading session, MasterCard (MA)...",NaN,NaN,NaN
1,2023-07-11,Mastercard (MA) & JazzCash to Speed Up Digitiz...,Mastercard (MA) partners with JazzCash to driv...,NaN,NaN,NaN
2,2023-07-13,Mastercard (MA) & Vodafone to Drive Financial ...,Mastercard (MA) partners with Vodafone to driv...,NaN,NaN,NaN
3,2023-07-13,FIS or MA: Which Is the Better Value Stock Rig...,FIS vs. MA: Which Stock Is the Better Value Op...,NaN,NaN,NaN
4,2023-07-13,1 Spectacular Warren Buffett Dividend Stock Th...,Warren Buffett is not against investing in div...,NaN,NaN,NaN
...,...,...,...,...,...,...
909,2026-02-01,Affiance Financial Bets $43 Million on Chuck A...,Affiance Financial initiated a new $43 million...,positive,NaN,NaN
910,2026-02-02,Why a 2.1% Portfolio Shift Targets a New ETF W...,Capital Planning LLC initiated a new position ...,positive,NaN,NaN
911,2026-02-03,Here's Why Mastercard Stock Is Still a Buy Des...,Despite regulatory headwinds from a proposed 1...,positive,negative,negative
912,2026-02-04,Behavioral Biometrics Market to Reach US$ 18.3...,The global behavioral biometrics market is pro...,positive,NaN,NaN
913,2026-02-08,Visa and Mastercard Execs Recently Dismissed S...,Visa and Mastercard executives have dismissed ...,negative,NaN,NaN

In [62]:
test_news = data.iloc[0]

In [63]:
test_news.title

'MasterCard (MA) Outpaces Stock Market Gains: What You Should Know'

In [ ]:
#ahora voy a hacer un score para cada noticia.

In [66]:
data["news_score"] = data.real_news.apply(nlp)

In [67]:
len(data)

914

In [68]:
data

,date,title,real_news,ma,axp,cof,news_score
0,2023-07-11,MasterCard (MA) Outpaces Stock Market Gains: W...,"In the latest trading session, MasterCard (MA)...",NaN,NaN,NaN,"[{'label': 'Neutral', 'score': 0.9994713664054..."
1,2023-07-11,Mastercard (MA) & JazzCash to Speed Up Digitiz...,Mastercard (MA) partners with JazzCash to driv...,NaN,NaN,NaN,"[{'label': 'Neutral', 'score': 0.9669819474220..."
2,2023-07-13,Mastercard (MA) & Vodafone to Drive Financial ...,Mastercard (MA) partners with Vodafone to driv...,NaN,NaN,NaN,"[{'label': 'Neutral', 'score': 0.99128258228302}]"
3,2023-07-13,FIS or MA: Which Is the Better Value Stock Rig...,FIS vs. MA: Which Stock Is the Better Value Op...,NaN,NaN,NaN,"[{'label': 'Neutral', 'score': 0.9975883960723..."
4,2023-07-13,1 Spectacular Warren Buffett Dividend Stock Th...,Warren Buffett is not against investing in div...,NaN,NaN,NaN,"[{'label': 'Neutral', 'score': 0.9979544878005..."
...,...,...,...,...,...,...,...
909,2026-02-01,Affiance Financial Bets $43 Million on Chuck A...,Affiance Financial initiated a new $43 million...,positive,NaN,NaN,"[{'label': 'Positive', 'score': 0.577379822731..."
910,2026-02-02,Why a 2.1% Portfolio Shift Targets a New ETF W...,Capital Planning LLC initiated a new position ...,positive,NaN,NaN,"[{'label': 'Positive', 'score': 0.999998688697..."
911,2026-02-03,Here's Why Mastercard Stock Is Still a Buy Des...,Despite regulatory headwinds from a proposed 1...,positive,negative,negative,"[{'label': 'Positive', 'score': 1.0}]"
912,2026-02-04,Behavioral Biometrics Market to Reach US$ 18.3...,The global behavioral biometrics market is pro...,positive,NaN,NaN,"[{'label': 'Positive', 'score': 0.999985456466..."
913,2026-02-08,Visa and Mastercard Execs Recently Dismissed S...,Visa and Mastercard executives have dismissed ...,negative,NaN,NaN,"[{'label': 'Positive', 'score': 0.999999403953..."

In [69]:
filtrar_distintos_de_neutral = data[data["news_score"].apply(lambda news: news[0]["label"] != "Neutral" )]
filtrar_distintos_de_neutral

,date,title,real_news,ma,axp,cof,news_score
5,2023-07-13,Netflix To Rally More Than 11%? Here Are 10 Ot...,Mizuho boosted the price target for Gulfport ...,NaN,NaN,NaN,"[{'label': 'Positive', 'score': 0.999803006649..."
8,2023-07-14,Back-to-School Shopping to Fall? Stocks to Win...,Inflationary pressures are expected to dampen ...,NaN,NaN,NaN,"[{'label': 'Negative', 'score': 0.942589461803..."
9,2023-07-14,"Mastercard (MA), CrediMax to Boost Digital Pay...",Mastercard (MA) and CrediMax renew strategic p...,NaN,NaN,NaN,"[{'label': 'Positive', 'score': 0.999977827072..."
13,2023-07-15,Why You Should Aim For $3 Million For Retireme...,"Saving early and regularly, investing wisely, ...",NaN,NaN,NaN,"[{'label': 'Positive', 'score': 0.998208999633..."
14,2023-07-16,3 Warren Buffett Stocks to Buy Hand Over Fist ...,The legendary investor has a knack for finding...,NaN,NaN,NaN,"[{'label': 'Positive', 'score': 0.999767601490..."
...,...,...,...,...,...,...,...
909,2026-02-01,Affiance Financial Bets $43 Million on Chuck A...,Affiance Financial initiated a new $43 million...,positive,NaN,NaN,"[{'label': 'Positive', 'score': 0.577379822731..."
910,2026-02-02,Why a 2.1% Portfolio Shift Targets a New ETF W...,Capital Planning LLC initiated a new position ...,positive,NaN,NaN,"[{'label': 'Positive', 'score': 0.999998688697..."
911,2026-02-03,Here's Why Mastercard Stock Is Still a Buy Des...,Despite regulatory headwinds from a proposed 1...,positive,negative,negative,"[{'label': 'Positive', 'score': 1.0}]"
912,2026-02-04,Behavioral Biometrics Market to Reach US$ 18.3...,The global behavioral biometrics market is pro...,positive,NaN,NaN,"[{'label': 'Positive', 'score': 0.999985456466..."
913,2026-02-08,Visa and Mastercard Execs Recently Dismissed S...,Visa and Mastercard executives have dismissed ...,negative,NaN,NaN,"[{'label': 'Positive', 'score': 0.999999403953..."

In [72]:
data["news_score"] = data["news_score"].apply(lambda value: value[0]["score"])

In [73]:
data

,date,title,real_news,ma,axp,cof,news_score
0,2023-07-11,MasterCard (MA) Outpaces Stock Market Gains: W...,"In the latest trading session, MasterCard (MA)...",NaN,NaN,NaN,0.999471
1,2023-07-11,Mastercard (MA) & JazzCash to Speed Up Digitiz...,Mastercard (MA) partners with JazzCash to driv...,NaN,NaN,NaN,0.966982
2,2023-07-13,Mastercard (MA) & Vodafone to Drive Financial ...,Mastercard (MA) partners with Vodafone to driv...,NaN,NaN,NaN,0.991283
3,2023-07-13,FIS or MA: Which Is the Better Value Stock Rig...,FIS vs. MA: Which Stock Is the Better Value Op...,NaN,NaN,NaN,0.997588
4,2023-07-13,1 Spectacular Warren Buffett Dividend Stock Th...,Warren Buffett is not against investing in div...,NaN,NaN,NaN,0.997954
...,...,...,...,...,...,...,...
909,2026-02-01,Affiance Financial Bets $43 Million on Chuck A...,Affiance Financial initiated a new $43 million...,positive,NaN,NaN,0.577380
910,2026-02-02,Why a 2.1% Portfolio Shift Targets a New ETF W...,Capital Planning LLC initiated a new position ...,positive,NaN,NaN,0.999999
911,2026-02-03,Here's Why Mastercard Stock Is Still a Buy Des...,Despite regulatory headwinds from a proposed 1...,positive,negative,negative,1.000000
912,2026-02-04,Behavioral Biometrics Market to Reach US$ 18.3...,The global behavioral biometrics market is pro...,positive,NaN,NaN,0.999985
913,2026-02-08,Visa and Mastercard Execs Recently Dismissed S...,Visa and Mastercard executives have dismissed ...,negative,NaN,NaN,0.999999

In [74]:
data.to_csv("../data/csv/datos_2023-07-11_a_2026-02-08.csv")