In [2]:
import pandas as pd

In [3]:
data = pd.read_csv("../data/csv/final_data.csv")

In [4]:
data.drop(columns="Unnamed: 0", inplace=True)

In [5]:
data.set_index("Date", inplace=True)

In [6]:
data

,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits,ma,axp,cof,news_score
Date,,,,,,,,,,,,
2023-02-13,368.559998,371.140015,367.070007,370.829987,364.411774,2286400,0.0,0.0,0.0,0.0,0.0,0.0
2023-02-14,369.579987,373.410004,367.730011,369.959991,363.556854,1841400,0.0,0.0,0.0,0.0,0.0,0.0
2023-02-15,366.279999,369.799988,365.010010,369.640015,363.242401,2203300,0.0,0.0,0.0,0.0,0.0,0.0
2023-02-16,364.899994,373.079987,364.899994,367.549988,361.188568,2792700,0.0,0.0,0.0,0.0,0.0,0.0
2023-02-17,364.059998,366.700012,359.799988,361.130005,354.879669,2718900,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
2026-02-05,554.849976,561.919983,549.950012,551.890015,551.890015,4621600,0.0,0.0,0.0,0.0,0.0,0.0
2026-02-06,553.070007,556.789978,539.799988,548.739990,548.739990,3779700,0.0,0.0,0.0,0.0,0.0,0.0
2026-02-09,543.710022,546.559998,534.200012,535.330017,535.330017,4110300,0.0,0.0,0.0,0.0,0.0,0.0
2026-02-10,536.270020,547.000000,535.000000,540.390015,540.390015,2222700,0.0,0.0,0.0,0.0,0.0,0.0
2026-02-11,538.150024,540.700012,533.109985,537.460022,537.460022,3690903,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
data.loc[data.news_score != 0]

,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits,ma,axp,cof,news_score
Date,,,,,,,,,,,,
2023-07-11,393.619995,398.459991,392.339996,397.799988,392.094482,2106200,0.0,0.0,0.0,0.0,0.0,0.983227
2023-07-13,403.000000,403.239990,400.459991,400.559998,394.814880,2354900,0.0,0.0,0.0,0.0,0.0,0.996657
2023-07-14,402.119995,403.489990,400.299988,402.510010,396.736938,1978500,0.0,0.0,0.0,0.0,0.0,0.967316
2023-07-17,401.950012,404.000000,401.119995,402.200012,396.431396,2344500,0.0,0.0,0.0,0.0,0.0,0.880650
2023-07-18,400.420013,401.940002,395.209991,398.160004,392.449371,2676200,0.0,0.0,0.0,0.0,0.0,0.975566
...,...,...,...,...,...,...,...,...,...,...,...,...
2026-01-29,531.789978,544.239990,520.109985,543.729980,543.729980,5488300,0.0,0.0,0.0,0.0,0.0,0.999357
2026-01-30,541.010010,543.760010,535.229980,538.789978,538.789978,4306900,0.0,0.0,1.0,0.0,0.0,0.524995
2026-02-02,540.989990,557.119995,540.950012,555.369995,555.369995,4603300,0.0,0.0,1.0,0.0,0.0,0.999999
2026-02-03,554.330017,560.109985,549.030029,550.719971,550.719971,5706700,0.0,0.0,1.0,-1.0,-1.0,1.000000
2026-02-04,549.729980,556.599976,541.010010,553.520020,553.520020,4448000,0.0,0.0,1.0,0.0,0.0,0.999985

In [8]:
import yfinance as yf
mastercard = yf.Ticker("MA")
data_m = mastercard.history( start = "2022-08-13",end="2023-01-13", auto_adjust=False)

In [9]:
data_m.drop(columns=["Open","High","Low","Close","Volume","Dividends","Stock Splits"], inplace=True)

In [10]:
data.reset_index(inplace=True)

In [13]:
data_m.Date

0     2022-08-15 00:00:00-04:00
1     2022-08-16 00:00:00-04:00
2     2022-08-17 00:00:00-04:00
3     2022-08-18 00:00:00-04:00
4     2022-08-19 00:00:00-04:00
                 ...
100   2023-01-06 00:00:00-05:00
101   2023-01-09 00:00:00-05:00
102   2023-01-10 00:00:00-05:00
103   2023-01-11 00:00:00-05:00
104   2023-01-12 00:00:00-05:00
Name: Date, Length: 105, dtype: datetime64[ns, America/New_York]

In [12]:
data_m.reset_index(inplace=True)

In [14]:
data_m.Date = pd.to_datetime(str(data_m.Date)[4:16])

In [15]:
data.set_index(data.Date,inplace=True)
data_m.set_index(data_m.Date,inplace=True)

In [16]:
data_end = pd.concat([data,data_m],axis=0)

In [17]:
data_end

,Date,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits,ma,axp,cof,news_score
Date,,,,,,,,,,,,,
2023-02-13,2023-02-13,368.559998,371.140015,367.070007,370.829987,364.411774,2286400.0,0.0,0.0,0.0,0.0,0.0,0.0
2023-02-14,2023-02-14,369.579987,373.410004,367.730011,369.959991,363.556854,1841400.0,0.0,0.0,0.0,0.0,0.0,0.0
2023-02-15,2023-02-15,366.279999,369.799988,365.010010,369.640015,363.242401,2203300.0,0.0,0.0,0.0,0.0,0.0,0.0
2023-02-16,2023-02-16,364.899994,373.079987,364.899994,367.549988,361.188568,2792700.0,0.0,0.0,0.0,0.0,0.0,0.0
2023-02-17,2023-02-17,364.059998,366.700012,359.799988,361.130005,354.879669,2718900.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-08-15 00:00:00,2022-08-15 00:00:00,NaN,NaN,NaN,NaN,361.306458,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-08-15 00:00:00,2022-08-15 00:00:00,NaN,NaN,NaN,NaN,364.549408,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-08-15 00:00:00,2022-08-15 00:00:00,NaN,NaN,NaN,NaN,364.588684,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-08-15 00:00:00,2022-08-15 00:00:00,NaN,NaN,NaN,NaN,371.320160,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-08-15 00:00:00,2022-08-15 00:00:00,NaN,NaN,NaN,NaN,373.236328,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
data_end.index = pd.to_datetime(data_end.index)

In [19]:
data_end = data_end.sort_index()

In [20]:
data_end

,Date,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits,ma,axp,cof,news_score
Date,,,,,,,,,,,,,
2022-08-15,2022-08-15 00:00:00,NaN,NaN,NaN,NaN,373.236328,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-08-15,2022-08-15 00:00:00,NaN,NaN,NaN,NaN,287.567352,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-08-15,2022-08-15 00:00:00,NaN,NaN,NaN,NaN,284.168457,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-08-15,2022-08-15 00:00:00,NaN,NaN,NaN,NaN,280.612823,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-08-15,2022-08-15 00:00:00,NaN,NaN,NaN,NaN,284.237030,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-02-05,2026-02-05,554.849976,561.919983,549.950012,551.890015,551.890015,4621600.0,0.0,0.0,0.0,0.0,0.0,0.0
2026-02-06,2026-02-06,553.070007,556.789978,539.799988,548.739990,548.739990,3779700.0,0.0,0.0,0.0,0.0,0.0,0.0
2026-02-09,2026-02-09,543.710022,546.559998,534.200012,535.330017,535.330017,4110300.0,0.0,0.0,0.0,0.0,0.0,0.0
2026-02-10,2026-02-10,536.270020,547.000000,535.000000,540.390015,540.390015,2222700.0,0.0,0.0,0.0,0.0,0.0,0.0
2026-02-11,2026-02-11,538.150024,540.700012,533.109985,537.460022,537.460022,3690903.0,0.0,0.0,0.0,0.0,0.0,0.0

In [21]:
data_end["mm21"] = data_end["Adj Close"].rolling(21).mean()

In [22]:
data_end["mm50"] = data_end["Adj Close"].rolling(50).mean()

In [23]:
data_end["distancia_mm50"] = ((data_end["Adj Close"] - data_end["mm50"]) / data_end["mm50"]) * 100
data_end["distancia_mm21"] = ((data_end["Adj Close"] - data_end["mm21"]) / data_end["mm21"]) * 100

In [24]:
data_end

,Date,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits,ma,axp,cof,news_score,mm21,mm50,distancia_mm50,distancia_mm21
Date,,,,,,,,,,,,,,,,,
2022-08-15,2022-08-15 00:00:00,NaN,NaN,NaN,NaN,373.236328,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-08-15,2022-08-15 00:00:00,NaN,NaN,NaN,NaN,287.567352,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-08-15,2022-08-15 00:00:00,NaN,NaN,NaN,NaN,284.168457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-08-15,2022-08-15 00:00:00,NaN,NaN,NaN,NaN,280.612823,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-08-15,2022-08-15 00:00:00,NaN,NaN,NaN,NaN,284.237030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-02-05,2026-02-05,554.849976,561.919983,549.950012,551.890015,551.890015,4621600.0,0.0,0.0,0.0,0.0,0.0,0.0,545.432861,553.629700,-0.314233,1.183859
2026-02-06,2026-02-06,553.070007,556.789978,539.799988,548.739990,548.739990,3779700.0,0.0,0.0,0.0,0.0,0.0,0.0,543.989519,553.863634,-0.925073,0.873265
2026-02-09,2026-02-09,543.710022,546.559998,534.200012,535.330017,535.330017,4110300.0,0.0,0.0,0.0,0.0,0.0,0.0,541.900472,553.657228,-3.310209,-1.212484
2026-02-10,2026-02-10,536.270020,547.000000,535.000000,540.390015,540.390015,2222700.0,0.0,0.0,0.0,0.0,0.0,0.0,540.226664,553.582775,-2.383159,0.030237
2026-02-11,2026-02-11,538.150024,540.700012,533.109985,537.460022,537.460022,3690903.0,0.0,0.0,0.0,0.0,0.0,0.0,538.854283,553.337888,-2.869470,-0.258745

In [25]:
data_end = data_end.loc[pd.to_datetime("2023-02-13"):pd.to_datetime("2026-02-11")]

In [26]:
data_end

,Date,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits,ma,axp,cof,news_score,mm21,mm50,distancia_mm50,distancia_mm21
Date,,,,,,,,,,,,,,,,,
2023-02-13,2023-02-13,368.559998,371.140015,367.070007,370.829987,364.411774,2286400.0,0.0,0.0,0.0,0.0,0.0,0.0,336.891792,338.675870,7.598978,8.168790
2023-02-14,2023-02-14,369.579987,373.410004,367.730011,369.959991,363.556854,1841400.0,0.0,0.0,0.0,0.0,0.0,0.0,339.014258,338.918995,7.269542,7.239400
2023-02-15,2023-02-15,366.279999,369.799988,365.010010,369.640015,363.242401,2203300.0,0.0,0.0,0.0,0.0,0.0,0.0,341.092784,339.175845,7.095598,6.493722
2023-02-16,2023-02-16,364.899994,373.079987,364.899994,367.549988,361.188568,2792700.0,0.0,0.0,0.0,0.0,0.0,0.0,343.545837,339.384554,6.424575,5.135481
2023-02-17,2023-02-17,364.059998,366.700012,359.799988,361.130005,354.879669,2718900.0,0.0,0.0,0.0,0.0,0.0,0.0,344.687935,339.688029,4.472233,2.956801
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-02-05,2026-02-05,554.849976,561.919983,549.950012,551.890015,551.890015,4621600.0,0.0,0.0,0.0,0.0,0.0,0.0,545.432861,553.629700,-0.314233,1.183859
2026-02-06,2026-02-06,553.070007,556.789978,539.799988,548.739990,548.739990,3779700.0,0.0,0.0,0.0,0.0,0.0,0.0,543.989519,553.863634,-0.925073,0.873265
2026-02-09,2026-02-09,543.710022,546.559998,534.200012,535.330017,535.330017,4110300.0,0.0,0.0,0.0,0.0,0.0,0.0,541.900472,553.657228,-3.310209,-1.212484
2026-02-10,2026-02-10,536.270020,547.000000,535.000000,540.390015,540.390015,2222700.0,0.0,0.0,0.0,0.0,0.0,0.0,540.226664,553.582775,-2.383159,0.030237
2026-02-11,2026-02-11,538.150024,540.700012,533.109985,537.460022,537.460022,3690903.0,0.0,0.0,0.0,0.0,0.0,0.0,538.854283,553.337888,-2.869470,-0.258745

In [27]:
data_end.drop(columns="Date", inplace= True)

C:\Users\Usuario\AppData\Local\Temp\ipykernel_22884\3025943432.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_end.drop(columns="Date", inplace= True)

In [30]:
data_end.to_csv("./csv/procesed_data.csv")