In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
from datetime import date

In [4]:
data = pd.read_csv("../data/csv/datos_terminados.csv")

In [5]:
data.set_index("date", inplace= True)

In [6]:
data.isnull().sum()

ma            0
axp           0
cof           0
news_score    0
dtype: int64

In [8]:
import yfinance as yf

In [8]:
mastercard = yf.Ticker("MA")

In [9]:
mastercard_data  = mastercard.history(period = '3y', auto_adjust= False)

In [10]:
data

             ma  axp  cof  news_score
date
2023-07-11  0.0  0.0  0.0    0.983227
2023-07-12  0.0  0.0  0.0    0.000000
2023-07-13  0.0  0.0  0.0    0.996657
2023-07-14  0.0  0.0  0.0    0.967316
2023-07-15  0.0  0.0  0.0    0.995629
...         ...  ...  ...         ...
2026-02-04  1.0  0.0  0.0    0.999985
2026-02-05  0.0  0.0  0.0    0.000000
2026-02-06  0.0  0.0  0.0    0.000000
2026-02-07  0.0  0.0  0.0    0.000000
2026-02-08 -1.0  0.0  0.0    0.999999

[944 rows x 4 columns]

In [11]:
data = data.loc[data.news_score != 0.0]

In [12]:
data

             ma  axp  cof  news_score
date
2023-07-11  0.0  0.0  0.0    0.983227
2023-07-13  0.0  0.0  0.0    0.996657
2023-07-14  0.0  0.0  0.0    0.967316
2023-07-15  0.0  0.0  0.0    0.995629
2023-07-16  0.0  0.0  0.0    0.999768
...         ...  ...  ...         ...
2026-02-01  1.0  0.0  0.0    0.788689
2026-02-02  1.0  0.0  0.0    0.999999
2026-02-03  1.0 -1.0 -1.0    1.000000
2026-02-04  1.0  0.0  0.0    0.999985
2026-02-08 -1.0  0.0  0.0    0.999999

[469 rows x 4 columns]

In [13]:
data_test = data.copy()

In [14]:
data_test

             ma  axp  cof  news_score
date
2023-07-11  0.0  0.0  0.0    0.983227
2023-07-13  0.0  0.0  0.0    0.996657
2023-07-14  0.0  0.0  0.0    0.967316
2023-07-15  0.0  0.0  0.0    0.995629
2023-07-16  0.0  0.0  0.0    0.999768
...         ...  ...  ...         ...
2026-02-01  1.0  0.0  0.0    0.788689
2026-02-02  1.0  0.0  0.0    0.999999
2026-02-03  1.0 -1.0 -1.0    1.000000
2026-02-04  1.0  0.0  0.0    0.999985
2026-02-08 -1.0  0.0  0.0    0.999999

[469 rows x 4 columns]

In [15]:
mastercard_data

,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits
Date,,,,,,,,
2023-02-13 00:00:00-05:00,368.559998,371.140015,367.070007,370.829987,364.411774,2286400,0.0,0.0
2023-02-14 00:00:00-05:00,369.579987,373.410004,367.730011,369.959991,363.556854,1841400,0.0,0.0
2023-02-15 00:00:00-05:00,366.279999,369.799988,365.010010,369.640015,363.242401,2203300,0.0,0.0
2023-02-16 00:00:00-05:00,364.899994,373.079987,364.899994,367.549988,361.188568,2792700,0.0,0.0
2023-02-17 00:00:00-05:00,364.059998,366.700012,359.799988,361.130005,354.879669,2718900,0.0,0.0
...,...,...,...,...,...,...,...,...
2026-02-05 00:00:00-05:00,554.849976,561.919983,549.950012,551.890015,551.890015,4621600,0.0,0.0
2026-02-06 00:00:00-05:00,553.070007,556.789978,539.799988,548.739990,548.739990,3779700,0.0,0.0
2026-02-09 00:00:00-05:00,543.710022,546.559998,534.200012,535.330017,535.330017,4110300,0.0,0.0
2026-02-10 00:00:00-05:00,536.270020,547.000000,535.000000,540.390015,540.390015,2222700,0.0,0.0
2026-02-11 00:00:00-05:00,538.150024,540.700012,533.109985,537.460022,537.460022,3690903,0.0,0.0

In [16]:
mastercard_data.reset_index(inplace=True)

In [17]:
mastercard_data["Date"] = mastercard_data["Date"].apply(lambda x: str(x)[:10])

In [18]:
mastercard_data["Date"] = pd.to_datetime(mastercard_data["Date"]).dt.normalize()

In [19]:
mastercard_data

,Date,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits
0,2023-02-13,368.559998,371.140015,367.070007,370.829987,364.411774,2286400,0.0,0.0
1,2023-02-14,369.579987,373.410004,367.730011,369.959991,363.556854,1841400,0.0,0.0
2,2023-02-15,366.279999,369.799988,365.010010,369.640015,363.242401,2203300,0.0,0.0
3,2023-02-16,364.899994,373.079987,364.899994,367.549988,361.188568,2792700,0.0,0.0
4,2023-02-17,364.059998,366.700012,359.799988,361.130005,354.879669,2718900,0.0,0.0
...,...,...,...,...,...,...,...,...,...
747,2026-02-05,554.849976,561.919983,549.950012,551.890015,551.890015,4621600,0.0,0.0
748,2026-02-06,553.070007,556.789978,539.799988,548.739990,548.739990,3779700,0.0,0.0
749,2026-02-09,543.710022,546.559998,534.200012,535.330017,535.330017,4110300,0.0,0.0
750,2026-02-10,536.270020,547.000000,535.000000,540.390015,540.390015,2222700,0.0,0.0
751,2026-02-11,538.150024,540.700012,533.109985,537.460022,537.460022,3690903,0.0,0.0

In [20]:
data_test.reset_index(inplace=True)

In [21]:
data_test.rename(columns={"date": "Date"}, inplace=True)

In [22]:
type(mastercard_data.loc[0].Date)

pandas._libs.tslibs.timestamps.Timestamp

In [23]:
type(data_test.loc[0].Date)

str

In [24]:
data_test["Date"] = pd.to_datetime(data_test["Date"]).dt.normalize()

In [25]:
df_unido = pd.merge(mastercard_data, data_test, how="left", on = "Date")

In [33]:
df_unido

,Date,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits,ma,axp,cof,news_score
0,2023-02-13,368.559998,371.140015,367.070007,370.829987,364.411774,2286400,0.0,0.0,NaN,NaN,NaN,NaN
1,2023-02-14,369.579987,373.410004,367.730011,369.959991,363.556854,1841400,0.0,0.0,NaN,NaN,NaN,NaN
2,2023-02-15,366.279999,369.799988,365.010010,369.640015,363.242401,2203300,0.0,0.0,NaN,NaN,NaN,NaN
3,2023-02-16,364.899994,373.079987,364.899994,367.549988,361.188568,2792700,0.0,0.0,NaN,NaN,NaN,NaN
4,2023-02-17,364.059998,366.700012,359.799988,361.130005,354.879669,2718900,0.0,0.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
747,2026-02-05,554.849976,561.919983,549.950012,551.890015,551.890015,4621600,0.0,0.0,NaN,NaN,NaN,NaN
748,2026-02-06,553.070007,556.789978,539.799988,548.739990,548.739990,3779700,0.0,0.0,NaN,NaN,NaN,NaN
749,2026-02-09,543.710022,546.559998,534.200012,535.330017,535.330017,4110300,0.0,0.0,NaN,NaN,NaN,NaN
750,2026-02-10,536.270020,547.000000,535.000000,540.390015,540.390015,2222700,0.0,0.0,NaN,NaN,NaN,NaN
751,2026-02-11,538.150024,540.700012,533.109985,537.460022,537.460022,3690903,0.0,0.0,NaN,NaN,NaN,NaN

In [27]:
df_unido.loc[df_unido.ma == 0.25]

,Date,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits,ma,axp,cof,news_score
360,2024-07-22,445.410004,448.850006,443.25,447.940002,444.122559,2111700,0.0,0.0,0.25,0.0,0.0,0.999998

In [28]:
data_test.loc[0].Date, mastercard_data.loc[0].Date

(Timestamp('2023-07-11 00:00:00'), Timestamp('2023-02-13 00:00:00'))

In [29]:
import numpy as np

In [34]:
df_unido = df_unido.fillna(0)

In [35]:
df_unido

,Date,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits,ma,axp,cof,news_score
0,2023-02-13,368.559998,371.140015,367.070007,370.829987,364.411774,2286400,0.0,0.0,0.0,0.0,0.0,0.0
1,2023-02-14,369.579987,373.410004,367.730011,369.959991,363.556854,1841400,0.0,0.0,0.0,0.0,0.0,0.0
2,2023-02-15,366.279999,369.799988,365.010010,369.640015,363.242401,2203300,0.0,0.0,0.0,0.0,0.0,0.0
3,2023-02-16,364.899994,373.079987,364.899994,367.549988,361.188568,2792700,0.0,0.0,0.0,0.0,0.0,0.0
4,2023-02-17,364.059998,366.700012,359.799988,361.130005,354.879669,2718900,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
747,2026-02-05,554.849976,561.919983,549.950012,551.890015,551.890015,4621600,0.0,0.0,0.0,0.0,0.0,0.0
748,2026-02-06,553.070007,556.789978,539.799988,548.739990,548.739990,3779700,0.0,0.0,0.0,0.0,0.0,0.0
749,2026-02-09,543.710022,546.559998,534.200012,535.330017,535.330017,4110300,0.0,0.0,0.0,0.0,0.0,0.0
750,2026-02-10,536.270020,547.000000,535.000000,540.390015,540.390015,2222700,0.0,0.0,0.0,0.0,0.0,0.0
751,2026-02-11,538.150024,540.700012,533.109985,537.460022,537.460022,3690903,0.0,0.0,0.0,0.0,0.0,0.0

In [36]:
df_unido.to_csv("../data/csv/final_data.csv")

In [16]:
news_data = pd.read_csv('../../data/csv/final.csv')
stock_data = pd.read_csv('../../data/csv/stock_values_from_2024-01-01_to_2026-03-04.csv')

In [17]:
news_data

,date,title,real_news,ma,axp,cof,es_ingles,news_score
0,2026-03-04 00:00:00+00:00,Bitget Wallet amplía su tarjeta cripto sin com...,Bitget Wallet has launched a crypto payment ca...,0.0,0.0,0.0,True,0.000000
1,2026-03-04 00:00:00+00:00,Meta Is Bringing Back Stablecoin Payments—This...,Meta plans to launch a stablecoin with a third...,0.0,0.0,0.0,True,0.942217
2,2026-03-04 00:00:00+00:00,SoFi Gains Traction as Mastercard Deal Brings ...,SoFi Technologies announced an enhanced partne...,1.0,0.0,0.0,True,0.931969
3,2026-03-04 00:00:00+00:00,Bitget Wallet Expands Zero-Fee Crypto Card in ...,Bitget Wallet has launched a cryptocurrency pa...,0.0,0.0,0.0,True,0.000000
4,2026-03-03 00:00:00+00:00,"Stock Market Today, March 3: SoFi Technologies...",SoFi Technologies rose 1.22% to $18.61 on Marc...,1.0,0.0,0.0,True,0.965844
...,...,...,...,...,...,...,...,...
935,2023-07-18 00:00:00+00:00,Mastercard (MA) & Geidea Partner to Drive Paym...,Mastercard (MA) collaborates with Geidea to pr...,0.0,0.0,0.0,True,0.909683
936,2023-07-18 00:00:00+00:00,3 Payment Stocks Gaining From Improving Consum...,"Payment processors like Visa (V), Mastercard (...",0.0,0.0,0.0,True,0.930809
937,2023-07-18 00:00:00+00:00,3 Warren Buffett Stocks That Everyone Should Own,Let's take a page from the Oracle of Omaha's i...,0.0,0.0,0.0,True,0.000000
938,2023-07-17 00:00:00+00:00,MasterCard (MA) Stock Sinks As Market Gains: W...,MasterCard (MA) closed the most recent trading...,0.0,0.0,0.0,True,-0.547946
939,2023-07-17 00:00:00+00:00,Mastercard (MA) & DTS Unite to Minimize Digita...,Mastercard (MA) collaborates with DTS to provi...,0.0,0.0,0.0,True,0.906971

In [18]:
stock_data

,Date,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits
0,2024-01-02 00:00:00-05:00,424.089996,424.279999,419.559998,421.890015,416.441803,2463700,0.00,0.0
1,2024-01-03 00:00:00-05:00,421.200012,421.339996,417.500000,418.769989,413.362091,3093700,0.00,0.0
2,2024-01-04 00:00:00-05:00,418.500000,423.450012,418.279999,419.769989,414.349182,2042600,0.00,0.0
3,2024-01-05 00:00:00-05:00,420.489990,422.760010,416.989990,419.420013,414.003693,2415900,0.00,0.0
4,2024-01-08 00:00:00-05:00,419.440002,422.079987,416.529999,421.980011,417.187134,2125400,0.66,0.0
...,...,...,...,...,...,...,...,...,...
538,2026-02-25 00:00:00-05:00,502.820007,510.540009,502.420013,509.390015,509.390015,4139100,0.00,0.0
539,2026-02-26 00:00:00-05:00,510.950012,519.900024,509.010010,514.770020,514.770020,4843600,0.00,0.0
540,2026-02-27 00:00:00-05:00,509.470001,518.760010,506.750000,517.210022,517.210022,5121100,0.00,0.0
541,2026-03-02 00:00:00-05:00,509.480011,526.159973,507.339996,521.000000,521.000000,3827000,0.00,0.0
542,2026-03-03 00:00:00-05:00,513.609985,526.799988,513.000000,524.320007,524.320007,4199700,0.00,0.0

In [9]:
final_test = pd.read_csv('../../data/csv/merged_final.csv')
final_test

,Date,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits,ma,axp,cof,news_score
0,2024-01-02 00:00:00-05:00,424.089996,424.279999,419.559998,421.890015,416.441803,2463700,0.00,0.0,NaN,NaN,NaN,NaN
1,2024-01-03 00:00:00-05:00,421.200012,421.339996,417.500000,418.769989,413.362091,3093700,0.00,0.0,NaN,NaN,NaN,NaN
2,2024-01-04 00:00:00-05:00,418.500000,423.450012,418.279999,419.769989,414.349182,2042600,0.00,0.0,NaN,NaN,NaN,NaN
3,2024-01-05 00:00:00-05:00,420.489990,422.760010,416.989990,419.420013,414.003693,2415900,0.00,0.0,NaN,NaN,NaN,NaN
4,2024-01-08 00:00:00-05:00,419.440002,422.079987,416.529999,421.980011,417.187134,2125400,0.66,0.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
538,2026-02-25 00:00:00-05:00,502.820007,510.540009,502.420013,509.390015,509.390015,4139100,0.00,0.0,NaN,NaN,NaN,NaN
539,2026-02-26 00:00:00-05:00,510.950012,519.900024,509.010010,514.770020,514.770020,4843600,0.00,0.0,NaN,NaN,NaN,NaN
540,2026-02-27 00:00:00-05:00,509.470001,518.760010,506.750000,517.210022,517.210022,5121100,0.00,0.0,NaN,NaN,NaN,NaN
541,2026-03-02 00:00:00-05:00,509.480011,526.159973,507.339996,521.000000,521.000000,3827000,0.00,0.0,NaN,NaN,NaN,NaN
542,2026-03-03 00:00:00-05:00,513.609985,526.799988,513.000000,524.320007,524.320007,4199700,0.00,0.0,NaN,NaN,NaN,NaN

In [5]:
final_test = pd.read_csv('../../data/csv/final.csv')

In [6]:
final_test

,date,title,real_news,ma,axp,cof,es_ingles,news_score
0,2026-03-04 00:00:00+00:00,Bitget Wallet amplía su tarjeta cripto sin com...,Bitget Wallet has launched a crypto payment ca...,0.0,0.0,0.0,True,0.000000
1,2026-03-04 00:00:00+00:00,Meta Is Bringing Back Stablecoin Payments—This...,Meta plans to launch a stablecoin with a third...,0.0,0.0,0.0,True,0.942217
2,2026-03-04 00:00:00+00:00,SoFi Gains Traction as Mastercard Deal Brings ...,SoFi Technologies announced an enhanced partne...,1.0,0.0,0.0,True,0.931969
3,2026-03-04 00:00:00+00:00,Bitget Wallet Expands Zero-Fee Crypto Card in ...,Bitget Wallet has launched a cryptocurrency pa...,0.0,0.0,0.0,True,0.000000
4,2026-03-03 00:00:00+00:00,"Stock Market Today, March 3: SoFi Technologies...",SoFi Technologies rose 1.22% to $18.61 on Marc...,1.0,0.0,0.0,True,0.965844
...,...,...,...,...,...,...,...,...
935,2023-07-18 00:00:00+00:00,Mastercard (MA) & Geidea Partner to Drive Paym...,Mastercard (MA) collaborates with Geidea to pr...,0.0,0.0,0.0,True,0.909683
936,2023-07-18 00:00:00+00:00,3 Payment Stocks Gaining From Improving Consum...,"Payment processors like Visa (V), Mastercard (...",0.0,0.0,0.0,True,0.930809
937,2023-07-18 00:00:00+00:00,3 Warren Buffett Stocks That Everyone Should Own,Let's take a page from the Oracle of Omaha's i...,0.0,0.0,0.0,True,0.000000
938,2023-07-17 00:00:00+00:00,MasterCard (MA) Stock Sinks As Market Gains: W...,MasterCard (MA) closed the most recent trading...,0.0,0.0,0.0,True,-0.547946
939,2023-07-17 00:00:00+00:00,Mastercard (MA) & DTS Unite to Minimize Digita...,Mastercard (MA) collaborates with DTS to provi...,0.0,0.0,0.0,True,0.906971

In [7]:
type(final_test.loc[0]['ma'])

numpy.float64

In [ ]:
data_values = pd.read_csv('../../data/csv/stock_values_from_2023-07-17_to_2026-03-04.csv')
news_values = pd.read_csv('../../data/csv/final.csv')

In [24]:
data_values

,Date,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits
0,2023-07-17 00:00:00-04:00,401.950012,404.000000,401.119995,402.200012,396.431427,2344500,0.0,0.0
1,2023-07-18 00:00:00-04:00,400.420013,401.940002,395.209991,398.160004,392.449341,2676200,0.0,0.0
2,2023-07-19 00:00:00-04:00,398.000000,399.850006,396.309998,398.269989,392.557831,1809700,0.0,0.0
3,2023-07-20 00:00:00-04:00,397.140015,399.720001,395.549988,398.059998,392.350800,2570700,0.0,0.0
4,2023-07-21 00:00:00-04:00,398.670013,401.510010,397.420013,397.489990,391.788940,1868100,0.0,0.0
...,...,...,...,...,...,...,...,...,...
655,2026-02-25 00:00:00-05:00,502.820007,510.540009,502.420013,509.390015,509.390015,4139100,0.0,0.0
656,2026-02-26 00:00:00-05:00,510.950012,519.900024,509.010010,514.770020,514.770020,4843600,0.0,0.0
657,2026-02-27 00:00:00-05:00,509.470001,518.760010,506.750000,517.210022,517.210022,5121100,0.0,0.0
658,2026-03-02 00:00:00-05:00,509.480011,526.159973,507.339996,521.000000,521.000000,3827000,0.0,0.0
659,2026-03-03 00:00:00-05:00,513.609985,526.799988,513.000000,524.320007,524.320007,4199700,0.0,0.0

In [16]:
news_values

,date,title,real_news,ma,axp,cof,es_ingles,news_score
0,2026-03-04 00:00:00+00:00,Bitget Wallet amplía su tarjeta cripto sin com...,Bitget Wallet has launched a crypto payment ca...,0.0,0.0,0.0,True,0.000000
1,2026-03-04 00:00:00+00:00,Meta Is Bringing Back Stablecoin Payments—This...,Meta plans to launch a stablecoin with a third...,0.0,0.0,0.0,True,0.942217
2,2026-03-04 00:00:00+00:00,SoFi Gains Traction as Mastercard Deal Brings ...,SoFi Technologies announced an enhanced partne...,1.0,0.0,0.0,True,0.931969
3,2026-03-04 00:00:00+00:00,Bitget Wallet Expands Zero-Fee Crypto Card in ...,Bitget Wallet has launched a cryptocurrency pa...,0.0,0.0,0.0,True,0.000000
4,2026-03-03 00:00:00+00:00,"Stock Market Today, March 3: SoFi Technologies...",SoFi Technologies rose 1.22% to $18.61 on Marc...,1.0,0.0,0.0,True,0.965844
...,...,...,...,...,...,...,...,...
935,2023-07-18 00:00:00+00:00,Mastercard (MA) & Geidea Partner to Drive Paym...,Mastercard (MA) collaborates with Geidea to pr...,0.0,0.0,0.0,True,0.909683
936,2023-07-18 00:00:00+00:00,3 Payment Stocks Gaining From Improving Consum...,"Payment processors like Visa (V), Mastercard (...",0.0,0.0,0.0,True,0.930809
937,2023-07-18 00:00:00+00:00,3 Warren Buffett Stocks That Everyone Should Own,Let's take a page from the Oracle of Omaha's i...,0.0,0.0,0.0,True,0.000000
938,2023-07-17 00:00:00+00:00,MasterCard (MA) Stock Sinks As Market Gains: W...,MasterCard (MA) closed the most recent trading...,0.0,0.0,0.0,True,-0.547946
939,2023-07-17 00:00:00+00:00,Mastercard (MA) & DTS Unite to Minimize Digita...,Mastercard (MA) collaborates with DTS to provi...,0.0,0.0,0.0,True,0.906971

In [17]:
news_values.drop(['title','real_news'], axis=1, inplace=True)
news_values = news_values.groupby('date').agg({
    'ma':'mean',
    'axp': 'mean',
    'cof':'mean',
    'news_score':'mean'
})

In [19]:
news_values.reset_index(inplace=True)

In [21]:
news_values.rename(columns={"date" : 'Date'}, inplace=True)

In [30]:
news_values['Date'] = pd.to_datetime(news_values['Date'], utc=True).dt.tz_localize(None).dt.normalize()
data_values['Date'] = pd.to_datetime(data_values['Date'], utc=True).dt.tz_localize(None).dt.normalize()

In [31]:
data_values

,Date,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits
0,2023-07-17,401.950012,404.000000,401.119995,402.200012,396.431427,2344500,0.0,0.0
1,2023-07-18,400.420013,401.940002,395.209991,398.160004,392.449341,2676200,0.0,0.0
2,2023-07-19,398.000000,399.850006,396.309998,398.269989,392.557831,1809700,0.0,0.0
3,2023-07-20,397.140015,399.720001,395.549988,398.059998,392.350800,2570700,0.0,0.0
4,2023-07-21,398.670013,401.510010,397.420013,397.489990,391.788940,1868100,0.0,0.0
...,...,...,...,...,...,...,...,...,...
655,2026-02-25,502.820007,510.540009,502.420013,509.390015,509.390015,4139100,0.0,0.0
656,2026-02-26,510.950012,519.900024,509.010010,514.770020,514.770020,4843600,0.0,0.0
657,2026-02-27,509.470001,518.760010,506.750000,517.210022,517.210022,5121100,0.0,0.0
658,2026-03-02,509.480011,526.159973,507.339996,521.000000,521.000000,3827000,0.0,0.0
659,2026-03-03,513.609985,526.799988,513.000000,524.320007,524.320007,4199700,0.0,0.0

In [33]:
hola = pd.merge(data_values,news_values,how='left',on='Date')

In [36]:
hola.loc[hola['news_score'] != 0]

,Date,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits,ma,axp,cof,news_score
0,2023-07-17,401.950012,404.000000,401.119995,402.200012,396.431427,2344500,0.0,0.0,0.0,0.0,0.0,0.179513
1,2023-07-18,400.420013,401.940002,395.209991,398.160004,392.449341,2676200,0.0,0.0,0.0,0.0,0.0,0.613497
2,2023-07-19,398.000000,399.850006,396.309998,398.269989,392.557831,1809700,0.0,0.0,0.0,0.0,0.0,0.037092
5,2023-07-24,397.480011,404.910004,396.609985,404.790009,398.984283,3029800,0.0,0.0,0.0,0.0,0.0,0.415975
7,2023-07-26,399.179993,403.309998,395.750000,402.410004,396.638367,2572300,0.0,0.0,0.0,0.0,0.0,0.318649
...,...,...,...,...,...,...,...,...,...,...,...,...,...
654,2026-02-24,493.739990,499.250000,491.260010,498.000000,498.000000,5292900,0.0,0.0,NaN,NaN,NaN,NaN
655,2026-02-25,502.820007,510.540009,502.420013,509.390015,509.390015,4139100,0.0,0.0,NaN,NaN,NaN,NaN
656,2026-02-26,510.950012,519.900024,509.010010,514.770020,514.770020,4843600,0.0,0.0,NaN,NaN,NaN,NaN
658,2026-03-02,509.480011,526.159973,507.339996,521.000000,521.000000,3827000,0.0,0.0,NaN,NaN,NaN,NaN
659,2026-03-03,513.609985,526.799988,513.000000,524.320007,524.320007,4199700,0.0,0.0,0.0,0.0,0.0,-0.002829

In [37]:
news_values = pd.read_csv('../../data/csv/merged_final.csv')

In [38]:
news_values

,Date,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits,ma,axp,cof,news_score
0,2023-07-17,401.950012,404.000000,401.119995,402.200012,396.431427,2344500,0.0,0.0,0.0,0.0,0.0,0.179513
1,2023-07-18,400.420013,401.940002,395.209991,398.160004,392.449341,2676200,0.0,0.0,0.0,0.0,0.0,0.613497
2,2023-07-19,398.000000,399.850006,396.309998,398.269989,392.557831,1809700,0.0,0.0,0.0,0.0,0.0,0.037092
3,2023-07-20,397.140015,399.720001,395.549988,398.059998,392.350800,2570700,0.0,0.0,0.0,0.0,0.0,0.000000
4,2023-07-21,398.670013,401.510010,397.420013,397.489990,391.788940,1868100,0.0,0.0,0.0,0.0,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
655,2026-02-25,502.820007,510.540009,502.420013,509.390015,509.390015,4139100,0.0,0.0,NaN,NaN,NaN,NaN
656,2026-02-26,510.950012,519.900024,509.010010,514.770020,514.770020,4843600,0.0,0.0,NaN,NaN,NaN,NaN
657,2026-02-27,509.470001,518.760010,506.750000,517.210022,517.210022,5121100,0.0,0.0,0.0,1.0,0.0,0.000000
658,2026-03-02,509.480011,526.159973,507.339996,521.000000,521.000000,3827000,0.0,0.0,NaN,NaN,NaN,NaN
659,2026-03-03,513.609985,526.799988,513.000000,524.320007,524.320007,4199700,0.0,0.0,0.0,0.0,0.0,-0.002829

In [39]:
news_values['news_score'].isnull().sum()

np.int64(289)