In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
from datetime import date

In [4]:
data = pd.read_csv("../data/csv/datos_terminados.csv")

In [5]:
data.set_index("date", inplace= True)

In [6]:
data.isnull().sum()

ma            0
axp           0
cof           0
news_score    0
dtype: int64

In [7]:
import yfinance as yf

In [8]:
mastercard = yf.Ticker("MA")

In [9]:
mastercard_data  = mastercard.history(period = '3y', auto_adjust= False)

In [10]:
data

             ma  axp  cof  news_score
date
2023-07-11  0.0  0.0  0.0    0.983227
2023-07-12  0.0  0.0  0.0    0.000000
2023-07-13  0.0  0.0  0.0    0.996657
2023-07-14  0.0  0.0  0.0    0.967316
2023-07-15  0.0  0.0  0.0    0.995629
...         ...  ...  ...         ...
2026-02-04  1.0  0.0  0.0    0.999985
2026-02-05  0.0  0.0  0.0    0.000000
2026-02-06  0.0  0.0  0.0    0.000000
2026-02-07  0.0  0.0  0.0    0.000000
2026-02-08 -1.0  0.0  0.0    0.999999

[944 rows x 4 columns]

In [11]:
data = data.loc[data.news_score != 0.0]

In [12]:
data

             ma  axp  cof  news_score
date
2023-07-11  0.0  0.0  0.0    0.983227
2023-07-13  0.0  0.0  0.0    0.996657
2023-07-14  0.0  0.0  0.0    0.967316
2023-07-15  0.0  0.0  0.0    0.995629
2023-07-16  0.0  0.0  0.0    0.999768
...         ...  ...  ...         ...
2026-02-01  1.0  0.0  0.0    0.788689
2026-02-02  1.0  0.0  0.0    0.999999
2026-02-03  1.0 -1.0 -1.0    1.000000
2026-02-04  1.0  0.0  0.0    0.999985
2026-02-08 -1.0  0.0  0.0    0.999999

[469 rows x 4 columns]

In [13]:
data_test = data.copy()

In [14]:
data_test

             ma  axp  cof  news_score
date
2023-07-11  0.0  0.0  0.0    0.983227
2023-07-13  0.0  0.0  0.0    0.996657
2023-07-14  0.0  0.0  0.0    0.967316
2023-07-15  0.0  0.0  0.0    0.995629
2023-07-16  0.0  0.0  0.0    0.999768
...         ...  ...  ...         ...
2026-02-01  1.0  0.0  0.0    0.788689
2026-02-02  1.0  0.0  0.0    0.999999
2026-02-03  1.0 -1.0 -1.0    1.000000
2026-02-04  1.0  0.0  0.0    0.999985
2026-02-08 -1.0  0.0  0.0    0.999999

[469 rows x 4 columns]

In [15]:
mastercard_data

,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits
Date,,,,,,,,
2023-02-13 00:00:00-05:00,368.559998,371.140015,367.070007,370.829987,364.411774,2286400,0.0,0.0
2023-02-14 00:00:00-05:00,369.579987,373.410004,367.730011,369.959991,363.556854,1841400,0.0,0.0
2023-02-15 00:00:00-05:00,366.279999,369.799988,365.010010,369.640015,363.242401,2203300,0.0,0.0
2023-02-16 00:00:00-05:00,364.899994,373.079987,364.899994,367.549988,361.188568,2792700,0.0,0.0
2023-02-17 00:00:00-05:00,364.059998,366.700012,359.799988,361.130005,354.879669,2718900,0.0,0.0
...,...,...,...,...,...,...,...,...
2026-02-05 00:00:00-05:00,554.849976,561.919983,549.950012,551.890015,551.890015,4621600,0.0,0.0
2026-02-06 00:00:00-05:00,553.070007,556.789978,539.799988,548.739990,548.739990,3779700,0.0,0.0
2026-02-09 00:00:00-05:00,543.710022,546.559998,534.200012,535.330017,535.330017,4110300,0.0,0.0
2026-02-10 00:00:00-05:00,536.270020,547.000000,535.000000,540.390015,540.390015,2222700,0.0,0.0
2026-02-11 00:00:00-05:00,538.150024,540.700012,533.109985,537.460022,537.460022,3690903,0.0,0.0

In [16]:
mastercard_data.reset_index(inplace=True)

In [17]:
mastercard_data["Date"] = mastercard_data["Date"].apply(lambda x: str(x)[:10])

In [18]:
mastercard_data["Date"] = pd.to_datetime(mastercard_data["Date"]).dt.normalize()

In [19]:
mastercard_data

,Date,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits
0,2023-02-13,368.559998,371.140015,367.070007,370.829987,364.411774,2286400,0.0,0.0
1,2023-02-14,369.579987,373.410004,367.730011,369.959991,363.556854,1841400,0.0,0.0
2,2023-02-15,366.279999,369.799988,365.010010,369.640015,363.242401,2203300,0.0,0.0
3,2023-02-16,364.899994,373.079987,364.899994,367.549988,361.188568,2792700,0.0,0.0
4,2023-02-17,364.059998,366.700012,359.799988,361.130005,354.879669,2718900,0.0,0.0
...,...,...,...,...,...,...,...,...,...
747,2026-02-05,554.849976,561.919983,549.950012,551.890015,551.890015,4621600,0.0,0.0
748,2026-02-06,553.070007,556.789978,539.799988,548.739990,548.739990,3779700,0.0,0.0
749,2026-02-09,543.710022,546.559998,534.200012,535.330017,535.330017,4110300,0.0,0.0
750,2026-02-10,536.270020,547.000000,535.000000,540.390015,540.390015,2222700,0.0,0.0
751,2026-02-11,538.150024,540.700012,533.109985,537.460022,537.460022,3690903,0.0,0.0

In [20]:
data_test.reset_index(inplace=True)

In [21]:
data_test.rename(columns={"date": "Date"}, inplace=True)

In [22]:
type(mastercard_data.loc[0].Date)

pandas._libs.tslibs.timestamps.Timestamp

In [23]:
type(data_test.loc[0].Date)

str

In [24]:
data_test["Date"] = pd.to_datetime(data_test["Date"]).dt.normalize()

In [25]:
df_unido = pd.merge(mastercard_data, data_test, how="left", on = "Date")

In [33]:
df_unido

,Date,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits,ma,axp,cof,news_score
0,2023-02-13,368.559998,371.140015,367.070007,370.829987,364.411774,2286400,0.0,0.0,NaN,NaN,NaN,NaN
1,2023-02-14,369.579987,373.410004,367.730011,369.959991,363.556854,1841400,0.0,0.0,NaN,NaN,NaN,NaN
2,2023-02-15,366.279999,369.799988,365.010010,369.640015,363.242401,2203300,0.0,0.0,NaN,NaN,NaN,NaN
3,2023-02-16,364.899994,373.079987,364.899994,367.549988,361.188568,2792700,0.0,0.0,NaN,NaN,NaN,NaN
4,2023-02-17,364.059998,366.700012,359.799988,361.130005,354.879669,2718900,0.0,0.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
747,2026-02-05,554.849976,561.919983,549.950012,551.890015,551.890015,4621600,0.0,0.0,NaN,NaN,NaN,NaN
748,2026-02-06,553.070007,556.789978,539.799988,548.739990,548.739990,3779700,0.0,0.0,NaN,NaN,NaN,NaN
749,2026-02-09,543.710022,546.559998,534.200012,535.330017,535.330017,4110300,0.0,0.0,NaN,NaN,NaN,NaN
750,2026-02-10,536.270020,547.000000,535.000000,540.390015,540.390015,2222700,0.0,0.0,NaN,NaN,NaN,NaN
751,2026-02-11,538.150024,540.700012,533.109985,537.460022,537.460022,3690903,0.0,0.0,NaN,NaN,NaN,NaN

In [27]:
df_unido.loc[df_unido.ma == 0.25]

,Date,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits,ma,axp,cof,news_score
360,2024-07-22,445.410004,448.850006,443.25,447.940002,444.122559,2111700,0.0,0.0,0.25,0.0,0.0,0.999998

In [28]:
data_test.loc[0].Date, mastercard_data.loc[0].Date

(Timestamp('2023-07-11 00:00:00'), Timestamp('2023-02-13 00:00:00'))

In [29]:
import numpy as np

In [34]:
df_unido = df_unido.fillna(0)

In [35]:
df_unido

,Date,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits,ma,axp,cof,news_score
0,2023-02-13,368.559998,371.140015,367.070007,370.829987,364.411774,2286400,0.0,0.0,0.0,0.0,0.0,0.0
1,2023-02-14,369.579987,373.410004,367.730011,369.959991,363.556854,1841400,0.0,0.0,0.0,0.0,0.0,0.0
2,2023-02-15,366.279999,369.799988,365.010010,369.640015,363.242401,2203300,0.0,0.0,0.0,0.0,0.0,0.0
3,2023-02-16,364.899994,373.079987,364.899994,367.549988,361.188568,2792700,0.0,0.0,0.0,0.0,0.0,0.0
4,2023-02-17,364.059998,366.700012,359.799988,361.130005,354.879669,2718900,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
747,2026-02-05,554.849976,561.919983,549.950012,551.890015,551.890015,4621600,0.0,0.0,0.0,0.0,0.0,0.0
748,2026-02-06,553.070007,556.789978,539.799988,548.739990,548.739990,3779700,0.0,0.0,0.0,0.0,0.0,0.0
749,2026-02-09,543.710022,546.559998,534.200012,535.330017,535.330017,4110300,0.0,0.0,0.0,0.0,0.0,0.0
750,2026-02-10,536.270020,547.000000,535.000000,540.390015,540.390015,2222700,0.0,0.0,0.0,0.0,0.0,0.0
751,2026-02-11,538.150024,540.700012,533.109985,537.460022,537.460022,3690903,0.0,0.0,0.0,0.0,0.0,0.0

In [36]:
df_unido.to_csv("../data/csv/final_data.csv")